package-lock.json
package.json

I have moved `test` script from pre push to pre commit hook. I have also extended that with `prettier` which will fix all syntax issues on the fly and linter so we won't have to add another commit with fixes from linter

Adding linter, tests and prettier on pre commit hook

---

packages/core/src/index.ts

Export method to use externally.

Expose the 'use' operator

---

example/src/fakes/dao.fake.ts
packages/core/src/http.interface.ts
packages/core/src/middlewares/bodyParser.middleware.ts

added new http status and done minor fixes

style(core): minor fixes, added new http status

---

jest.config.js
package.json
tsconfig.spec.json

- added separate `tsconfig.spec.json` for test related build cases (it could be handy in the future when there will be some need to change TS build configuration)

build(jest): separated tsconfig for test related builds

---

.prettierignore
.prettierrc.json
example/src/app.ts
example/src/controllers/api.controller.ts
example/src/controllers/user.controller.ts
example/src/fakes/auth.fake.ts
example/src/fakes/dao.fake.ts
example/src/middlewares/auth.middleware.ts

```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
- updated example project with example of `use` operator for dummy authorization middleware
```
[ ] Yes
[x] No
```

feat(example): example of `use` operator

---

.prettierignore
.prettierrc.json
package-lock.json
package.json
packages/core/src/http.listener.ts
packages/core/src/response/response.handler.ts
packages/middleware-joi/test/unit/schema.spec.ts

```
[ ] Bugfix
[ ] Feature
```
- removed prettier from linter process
```
[ ] Yes
[x] No
```

build(prettier): removed prettier

---

packages/core/src/http.listener.ts

```
[ ] Bugfix
[ ] Feature
```
Issue Number: #43 
```
[ ] Yes
[x] No
```

fix(core): more correct solution for strictFunctionTypes flag

---

packages/core/src/operators/matchPath/matcher.factory.ts
packages/core/src/operators/matchPath/queryParams.factory.ts
packages/core/src/util/compose.util.ts

```
[ ] Bugfix
[ ] Feature
```
- more functional `matcherFactory` and `queryParamsFactory` thanks to function composition
- added dedicated `compose` utility function
```
[ ] Yes
[x] No
```

style(core): function composition for `matcherFactory` and `queryParamsFactory`

---

packages/core/src/index.spec.ts
packages/core/src/index.ts
packages/middleware-logger/src/index.ts
packages/middleware-logger/src/time.factory.spec.ts
packages/middleware-logger/src/time.factory.ts

```
[ ] Bugfix
[x] Feature
```
- export `@marblejs/core` `compose` to share between packages
```
[ ] Yes
[x] No
```

feat(core): export compose utility function from `core` package

---

benchmarks/middleware.js
package.json
packages/core/src/effects/effects.combiner.ts
packages/core/src/http.listener.ts

```
[ ] Bugfix
[ ] Feature
```
- middlewares composition was not optimized properly - it has some difficulties to compose a larger amount of middlewares
```
[ ] Yes
[x] No
```

perf(core): optimized middlewares composition

---

package-lock.json
packages/core/src/effects/effects.interface.ts
packages/core/src/error/error.effect.spec.ts
packages/core/src/error/error.effect.ts
packages/core/src/http.listener.spec.ts
packages/core/src/http.listener.ts
packages/core/src/index.ts

```
[ ] Bugfix
[x] Feature
```
There is an inconsistency with current error handler definition and naming. We need to rename error handler from `errorMiddleware` into `errorEffect` because error handler acts as an **Effect** instead of **Middleware**.
- Changed `httpListener` error handler attribute from `errorMiddleware` 👉 `errorEffect`.
```
[y] Yes
[ ] No
```
old bootstrapping way:
```javascript
const app = httpListener({
middlewares,
effects,
errorMiddleware,  👈
});
```
new bootstrapping way:
```javascript
const app = …
```

feat: errorMiddleware -> errorEffect

---

example/package-lock.json
example/package.json
package-lock.json
package.json

```
[ ] Bugfix
[ ] Feature
[x] Packages version bump
```
- Packages update:
-- `RxJS` 6.2.2
-- `TypeScript` 3.0.1
-- `ts-node` 7.0.1
-- `jest` 23.5.0
```
[ ] Yes
[x] No
```

update: packages version bump

---

packages/core/src/effects/specs/effects.combiner.spec.ts
packages/core/src/effects/specs/effects.factory.spec.ts
packages/core/src/error/specs/error.effect.spec.ts
packages/core/src/error/specs/error.model.spec.ts
packages/core/src/response/specs/response.handler.spec.ts
packages/core/src/response/specs/responseBody.factory.spec.ts
packages/core/src/response/specs/responseContentType.factory.spec.ts
packages/core/src/response/specs/responseHeaders.factory.spec.ts
packages/core/src/router/specs/queryParams.factory.spec.ts
packages/core/src/router/specs/router.factory.spec.ts
packages/core/src/router/specs/router.helper.spec.ts
packages/core/src/router/specs/router.spec.ts
packages/core/src/router/specs/urlParams.factory.spec.ts
packages/middleware-body/src/index.ts
packages/middleware-joi/src/index.ts
packages/middleware-joi/test/helpers/api.spec-util.ts
packages/middleware-logger/src/index.ts

```
[ ] Bugfix
[ ] Feature
```
- spec files are placed next to the tested files which makes really hard to identify proper files if there are more than 3 files inside folder tree view
- moved spec files to separate folder near tested files
- improved formatting for middlewares code
```
[ ] Yes
[x] No
```

style: minor code style improvements

---

package.json

```
[ ] Bugfix
[ ] Feature
```
- added `lerna` script for publishing canary (nightly) builds
```
[ ] Yes
[x] No
```

build(root): script for publishing canary builds

---

package.json
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
- added support for TypeScript v.3.1.x
```
[ ] Yes
[x] No
```

build(root): update to TypeScript v.3.1.x

---

packages/@integration/src/index.ts
packages/@integration/src/ws.listener.ts
packages/core/src/http.listener.spec.ts
packages/core/src/http.listener.ts
packages/core/src/server/server.factory.ts
packages/core/src/server/specs/server.factory.spec.ts
packages/websockets/src/listener/specs/websocket.listener.spec.ts
packages/websockets/src/listener/websocket.listener.ts

```
[ ] Bugfix
[x] Feature
```
- `@marblejs/core` - `httpListener` - `errorEffect` 👉 `effect$`
- `@marblejs/core` - `createServer` - `httpEventsHandler ` 👉 `event$`
- `@marblejs/websockets` - `webSocketListener ` - `connection ` 👉 `connection$`
- `@marblejs/websockets` - `webSocketListener ` - `error ` 👉 `error$`
- `@marblejs/websockets` - simplified `WebSocketListenerConfig ` type inference
```
[x] Yes
[ ] No
```

imp(core, web sockets): properties renaming of factory functions

---

packages/core/src/index.ts
packages/core/src/listener/http.listener.spec.ts
packages/core/src/listener/http.listener.ts
packages/core/src/server/server.factory.ts
packages/core/src/server/specs/server.factory.spec.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

imp(core): http.listener files reorganization

---

packages/middleware-joi/package.json
packages/middleware-joi/src/deprecation.js
packages/middleware-joi/src/validator.middleware.ts
packages/middleware-joi/test/integration/integration.spec.ts

```
[ ] Bugfix
[ ] Feature
[x] Package deprecation
```
- Deprecated `@marblejs/middleware-joi` package. New users should use `@marblejs/middleware-io` instead.
```
[x] Yes
[ ] No
```

imp(middlware-joi): package deprecation

---

README.md

```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
Typo in middleware list. 
Typo fixed.
```
[ ] Yes
[x] No
```
N/A

docs(all): fix middleware typo

---

packages/core/src/server/server.event.subscriber.ts
packages/core/src/server/server.event.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(core): added misssing server events parameters

---

packages/middleware-logger/src/logger.handler.ts
packages/middleware-logger/src/logger.model.ts
packages/middleware-logger/src/logger.util.ts
packages/middleware-logger/src/spec/logger.factory.spec.ts
packages/middleware-logger/src/spec/logger.util.spec.ts

```
[ ] Bugfix
[x] Feature
```
- **@marblejs/middleware-logger** `filter` function can handle only outgoing responses
Issue Number: #115 
- **@marblejs/middleware-logger** `filter` function can handle both incoming requests and outgoing responses
Extended `filter` function signature:
```typescript
filter: (res: HttpResponse, req: HttpRequest) => boolean
```
```
[ ] Yes
[x] No
```

feat(middleware-logger): filter incoming requests

---

packages/core/tsconfig.json
packages/middleware-body/tsconfig.json
packages/middleware-cors/tsconfig.json
packages/middleware-io/tsconfig.json
packages/middleware-joi/tsconfig.json
packages/middleware-jwt/tsconfig.json
packages/middleware-logger/tsconfig.json
packages/websockets/tsconfig.json
tsconfig.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

build(tsconfig): simplified packages tsconfigs

---

package.json
packages/@integration/package.json
packages/core/package.json
packages/middleware-body/package.json
packages/middleware-cors/package.json
packages/middleware-io/package.json
packages/middleware-joi/package.json
packages/middleware-jwt/package.json
packages/middleware-logger/package.json
packages/websockets/package.json
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

imp(all): set rxjs  peerDependency version to minor

---

packages/middleware-logger/src/logger.model.ts
packages/middleware-logger/src/logger.util.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(middleware-logger): fs.WriteStream -> WritableLike

---

README.md

```
[ ] Bugfix
[ ] Feature
```
Add Gitter badge on readme.

imp(all): add gitter badge on readme

---

packages/core/src/+internal/testing/metadata.helper.ts
packages/proxy/package.json
packages/testing/openApi.reporter.js
packages/testing/package.json
packages/testing/src/apiCollection.ts
packages/testing/src/apiDocument.helper.ts
packages/testing/src/apiDocument.ts
packages/testing/src/apiEndpoint.helper.ts
packages/testing/src/apiEndpoint.ts
packages/testing/src/apiResponse.ts
packages/testing/src/index.ts
packages/testing/src/openApi.reporter.helper.ts
packages/testing/src/openApi.reporter.ts
packages/testing/src/spec/testing.spec.ts
packages/testing/src/testApi.ts
packages/testing/src/testing.types.ts

```
[x] Bugfix
[ ] Feature
```
* Using environmental variables to determine if tests are running (fixes lacking metadata issue, allows server to run)
* Small Marble.js server handles documentation chunks (no chunk files are created)
* Created Jest reporter to collect chunks and return OpenAPI doc on the end
* Authorization support
```
[ ] Yes
[x] No
```
This is an improvement set for my previous PR regarding `@marblejs/testing` package.

imp(testing): bugfixes & improvements

---

packages/core/package.json
packages/core/src/+internal/testing/http.helper.ts
packages/core/src/+internal/testing/metadata.helper.ts
packages/core/src/http.interface.ts
packages/middleware-io/package.json
packages/middleware-io/src/index.ts
packages/middleware-io/src/io.json-schema.ts
packages/middleware-io/src/io.request.middleware.ts
packages/middleware-io/src/specs/io.json-schema.spec.ts
packages/middleware-io/src/specs/io.request.middleware.spec.ts
packages/testing/src/apiDocument.helper.ts
packages/testing/src/apiDocument.ts
packages/testing/src/apiEndpoint.helper.ts
packages/testing/src/apiRequest.ts
packages/testing/src/apiResponse.ts
packages/testing/src/openApi.reporter.helper.ts
packages/testing/src/spec/testing.spec.ts
packages/testing/src/testing.types.ts
yarn.lock

```
[ ] Bugfix
[x] Feature
```
We can't generate JSON Schema from `io-ts`.
* Support for JSON Schema in io-ts middleware
* Fixed generationOptions in testing/docs module (allows to skip unwanted headers)
* Added expectStatus() method to apiresponse
```
[ ] Yes
[x] No
```

imp(testing): JSON Schema generation

---

.gitignore
packages/@integration/package.json
packages/@integration/src/effects/static.effects.ts
packages/core/src/server/specs/server.factory.spec.ts
packages/middleware-body/src/body.middleware.ts
packages/middleware-body/src/body.util.ts
packages/middleware-io/src/io.request.middleware.ts
packages/middleware-multipart/README.md
packages/middleware-multipart/package.json
packages/middleware-multipart/src/index.ts
packages/middleware-multipart/src/multipart.interface.ts
packages/middleware-multipart/src/multipart.middleware.ts
packages/middleware-multipart/src/multipart.parser.field.ts
packages/middleware-multipart/src/multipart.parser.file.ts
packages/middleware-multipart/src/multipart.parser.ts
packages/middleware-multipart/src/multipart.util.ts
packages/middleware-multipart/src/specs/index.spec.ts
packages/middleware-multipart/src/specs/multipart.middleware.spec.ts
packages/middleware-multipart/src/specs/multipart.util.spec.ts
packages/middleware-multipart/tsconfig.json
yarn.lock

```
[ ] Bugfix
[x] Feature
```
- `@marblejs/middleware-multipart` - Added middleware for handling **multipart/form-data** requests based on popular [busboy](https://github.com/mscdex/busboy) library. See `README.md` for complete API overview.
- `@marblejs/middleware-body` - Don't parse multipart related content types
```
[ ] Yes
[x] No
```

feat(middleware-multipart): multipart/form-data middleware based on busboy library

---

packages/proxy/src/serverProxy.ts
packages/testing/src/apiRequest.ts
packages/testing/src/apiResponse.ts

```
[ ] Bugfix
[x] Feature
```
We can't use stream as a proxy body parameter.
We don't have any details about internal crashes.
We can use stream as proxy body parameter.
We have some more details for internal server errors (i.e. proxy errors)
```
[ ] Yes
[x] No
```

FEAT(Proxy Streaming)

---

packages/proxy/package.json
packages/proxy/src/serverProxy.ts
packages/serverless/package.json
packages/testing/package.json

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(proxy): write after end

---

packages/@integration/src/messaging/server.ts
packages/@integration/test/messaging.integration.spec.ts
packages/messaging/README.md
packages/messaging/src/server/messaging.server.spec.ts
packages/messaging/src/server/messaging.server.ts
packages/messaging/tsconfig.json

```
[ ] Bugfix
[x] Feature
```
- Microservice is bootstrapped via calling `createMicroservice(...).run()` method. 
- Replaced `createMicroservice(...).run()` method with thunk 👉
`createMicroservice(...)()`
```
[x] Yes
[ ] No
```

imp(messaging): replaced #createMicroservice #run method with thunk

---

packages/@integration/src/messaging/server.ts
packages/@integration/test/messaging.integration.spec.ts
packages/core/src/event/event.interface.ts
packages/messaging/src/effects/messaging.effects.interface.ts
packages/messaging/src/server/messaging.server.listener.ts
packages/messaging/src/server/messaging.server.spec.ts
packages/messaging/src/transport/strategies/amqp.strategy.ts
packages/messaging/src/transport/transport.interface.ts
packages/websockets/src/effects/ws-effects.interface.ts

```
[ ] Bugfix
[x] Feature
```
- **@marblejs/core** - added `raw` attribute to `Event` interface
- **@marblejs/messaging** - fixed an issue with discontinuous msg stream (eg. previously it was impossible to do event buffering)
- **@marblejs/messaging** - improved error handling
- **@marblejs/messaging** - improved msg ack/nack
```
[ ] Yes
[x] No
```

imp(messaging): continuous stream + improved error handling + improved nack/ack

---

.github/workflows/test.yml
package.json
packages/@integration/package.json
packages/core/package.json
packages/core/src/error/specs/error.model.spec.ts
packages/core/src/response/specs/response.handler.spec.ts
packages/core/src/router/specs/router.factory.spec.ts
packages/core/src/router/specs/router.params.factory.spec.ts
packages/messaging/package.json
packages/middleware-body/package.json
packages/middleware-cors/package.json
packages/middleware-io/package.json
packages/middleware-io/src/io.json-schema.ts
packages/middleware-joi/package.json
packages/middleware-jwt/package.json
packages/middleware-logger/package.json
packages/middleware-multipart/package.json
packages/websockets/package.json
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
- Added support for TypeScript v3.6
```
[ ] Yes
[x] No
```

imp(all): support for TypeScript v3.6

---

packages/core/src/+internal/files/fileReader.helper.spec.ts
packages/core/src/response/specs/responseContentType.factory.spec.ts
packages/middleware-body/src/specs/body.middleware.spec.ts
packages/middleware-multipart/src/specs/multipart.util.spec.ts
packages/websockets/src/operators/mapToServer/mapToServer.operator.spec.ts

```
[ ] Bugfix
[ ] Feature
[x] Other
```
```
[ ] Yes
[x] No
```

test(all): removed deprecation warnings

---

packages/messaging/src/server/messaging.server.listener.ts
packages/messaging/src/server/specs/messaging.server.amqp.spec.ts
packages/messaging/src/transport/strategies/amqp.strategy.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(messaging): RPC event missmach

---

packages/messaging/src/server/messaging.server.listener.ts
packages/messaging/src/server/specs/messaging.server.redis.spec.ts
packages/messaging/src/transport/strategies/redis.strategy.helper.ts
packages/messaging/src/transport/strategies/redis.strategy.ts
packages/messaging/src/util/messaging.test.util.ts

```
[x] Bugfix
[ ] Feature
```
- Node complains that `redis` module is not installed if transport Redis is NOT used.
- Redis transport layer is properly lazily loaded.
```
[ ] Yes
[x] No
```

fix(messaging): lazyload `redis` module

---

packages/@integration/src/messaging/client.ts
packages/@integration/src/messaging/server.ts
packages/core/src/context/context.hook.ts
packages/messaging/package.json
packages/messaging/src/index.ts
packages/messaging/src/middlewares/messaging.eventLogger.middleware.ts
packages/messaging/src/middlewares/messaging.statusLogger.middleware.ts
packages/messaging/src/server/messaging.server.listener.ts
packages/messaging/src/server/messaging.server.logger.ts
packages/messaging/src/server/messaging.server.tokens.ts
packages/messaging/src/server/messaging.server.ts
packages/messaging/src/server/specs/messaging.server.amqp.spec.ts
packages/messaging/src/server/specs/messaging.server.redis.spec.ts
packages/messaging/src/transport/strategies/amqp.strategy.ts
packages/messaging/src/transport/strategies/redis.strategy.ts
packages/messaging/src/transport/transport.interface.ts
packages/messaging/src/util/messaging.test.util.ts

```
[ ] Bugfix
[x] Feature
```
- `@marblejs/messaging` - default input/output loggers
- `@marblejs/messaging` - default server connection status loggers
- `@marblejs/messaging` - user is able to register custom logger via `LoggerToken`
```
[ ] Yes
[x] No
```

feat(messaging): default input/output/status loggers

---

package.json
packages/middleware-multipart/src/multipart.parser.field.ts
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
- support for TypeScript v3.7
```
[ ] Yes
[x] No
```

build(all): added support for TypeScript v3.7

---

packages/core/src/context/specs/context.hook.spec.ts

```
[ ] Bugfix
[ ] Feature
[x] Other... 
```
```
[ ] Yes
[x] No
```

test(core): #useContext

---

benchmarks/middlewares.js
benchmarks/routing.js

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

imp(benchmarks): updated benchmarks to use current API

---

packages/core/src/+internal/testing/metadata.helper.ts
packages/core/src/+internal/utils/array.util.ts
packages/core/src/+internal/utils/http.util.ts
packages/core/src/+internal/utils/index.ts
packages/core/src/http.interface.ts
packages/core/src/listener/http.listener.spec.ts
packages/core/src/listener/http.listener.ts
packages/core/src/response/response.handler.ts
packages/core/src/response/specs/response.handler.spec.ts
packages/core/src/server/server.factory.ts
packages/core/src/server/server.metadata.storage.ts
packages/core/src/server/server.tokens.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

feat(core): request metadata storage

---

packages/messaging/src/middlewares/messaging.eventLogger.middleware.ts
packages/messaging/src/middlewares/messaging.statusLogger.middleware.ts
packages/messaging/src/server/messaging.server.logger.ts

```
[x] Bugfix
[ ] Feature
```
- **@marblejs/messaging** middleware loggers are passing strings with ANSI escape codes 
- **@marblejs/messaging** error events are not properly passed to logger
```
[ ] Yes
[x] No
```

imp(messaging): removed chalk from logger middlewares

---

packages/middleware-multipart/src/specs/multipart.middleware.spec.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(middleware-multipart): randomly failing tests

---

.gitignore
package.json
packages/@integration/tsconfig.json
packages/core/tsconfig.json
packages/messaging/tsconfig.json
packages/middleware-body/tsconfig.json
packages/middleware-cors/tsconfig.json
packages/middleware-io/tsconfig.json
packages/middleware-joi/tsconfig.json
packages/middleware-jwt/tsconfig.json
packages/middleware-logger/tsconfig.json
packages/middleware-multipart/tsconfig.json
packages/websockets/tsconfig.json
tsconfig.json

```
[ ] Bugfix
[ ] Feature
```
- optimized build times via using TypeScript feature called "[Project references](https://www.typescriptlang.org/docs/handbook/project-references.html)"
- added declaration maps to compiled artifacts
```
[ ] Yes
[x] No
```

build(all): TypeScript project references

---

benchmarks/middlewares.js
benchmarks/routing.js
packages/@integration/src/messaging/server.ts
packages/core/src/event/event.interface.ts
packages/core/src/http/router/http.router.interface.ts
packages/core/src/http/router/http.router.matcher.ts
packages/core/src/http/router/http.router.resolver.v2.ts
packages/core/src/http/router/specs/http.router.resolver.v2.spec.ts
packages/core/src/http/server/http.server.listener.ts
packages/messaging/src/effects/messaging.effects.interface.ts
packages/messaging/src/middlewares/messaging.eventLogger.middleware.ts
packages/messaging/src/server/messaging.server.listener.ts
packages/messaging/src/server/specs/messaging.server.amqp.spec.ts
packages/messaging/src/server/specs/messaging.server.redis.spec.ts
packages/messaging/src/transport/strategies/amqp.strategy.ts
packages/messaging/src/util/messaging.test.util.ts

```
[x] Bugfix
[ ] Feature
```
[ ] No
```

fix(core, messaging): race conditions

---

packages/core/src/http/router/http.router.resolver.v2.ts

```
[x] Bugfix
[ ] Feature
```

fix(core): output, error streams

---

packages/core/src/http/router/http.router.resolver.v2.ts

```
[x] Bugfix
[ ] Feature
```

fix(core): output, error streams (v2)

---

packages/core/src/event/event.factory.ts

```
[x] Bugfix
[ ] Feature
```

fix(core): event factory

---

packages/core/src/http/router/specs/http.router.factory.spec.ts
packages/core/src/http/router/specs/http.router.resolver.v2.spec.ts

```
[ ] Bugfix
[ ] Feature
[x] Other
```
- **@marblejs/core** - `resolveRouting` - added test cases for concurrent requests
```
[ ] Yes
[x] No
```

test(core): #resolveRouting - concurrent requests - unit test

---

packages/@integration/src/messaging/client.ts
packages/@integration/src/messaging/server.ts
packages/messaging/src/client/messaging.client.interface.ts
packages/messaging/src/client/messaging.client.spec.ts
packages/messaging/src/client/messaging.client.ts
packages/messaging/src/transport/strategies/amqp.strategy.interface.ts
packages/messaging/src/transport/strategies/amqp.strategy.ts
packages/messaging/src/transport/strategies/redis.strategy.interface.ts
packages/messaging/src/transport/strategies/redis.strategy.ts
packages/messaging/src/transport/transport.interface.ts

```
[ ] Bugfix
[x] Feature
```
- **@marblejs/messaging** - timeout RPC events (defaults to 2 mins but can be configured)
- **@marblejs/messaging** - cleanup AMQP resources after timeout
- **@marblejs/messaging** - improved `messagingClient` interface, client is asynchronous so it needs to be bound to the server eagerly
```
[ ] Yes
[x] No
``

feat(messaging): timeout RPC events and cleanup AMQP resources

---

codecov.yml
package.json
packages/@integration/src/websockets/http.server.ts
packages/@integration/src/websockets/websockets.server.ts
packages/core/src/http/router/http.router.resolver.v2.ts
packages/core/src/index.ts
packages/core/src/logger/logger.ts
packages/middleware-io/test/io-ws.integration.spec.ts
packages/websockets/src/effects/websocket.effects.interface.ts
packages/websockets/src/error/specs/websocket.error.effect.spec.ts
packages/websockets/src/error/websocket.error.effect.ts
packages/websockets/src/middlewares/websockets.eventLogger.middleware.ts
packages/websockets/src/operators/broadcast/websocket.broadcast.operator.ts
packages/websockets/src/response/websocket.response.handler.ts
packages/websockets/src/server/specs/websocket.server.spec.ts
packages/websockets/src/server/websocket.server.helper.ts
packages/websockets/src/server/websocket.server.interface.ts
packages/websockets/src/server/websocket.server.listener.ts
packages/websockets/src/server/websocket.server.ts
packages/websockets/src/transformer/websocket.json.transformer.ts
packages/websockets/src/transformer/websocket.transformer.interface.ts

```
[x] Bugfix
[x] Feature
```
- **@marblejs/websockets** - integration with core Logger dependency
- **@marblejs/websockets** - log events: `listening`, `connection`, `incoming`, `outgoing` and `error`
- **@marblejs/core** - fixed empty '/' path for RequestLogger
```
[ ] Yes
[x] No
```

feat(websockets): integration with core Logger dependency

---

packages/@integration/src/http/index.ts
packages/@integration/src/messaging/client.ts
packages/@integration/src/messaging/server.ts
packages/@integration/src/websockets/http.server.ts
packages/core/src/http/error/http.error.effect.ts
packages/core/src/http/error/http.error.model.ts
packages/core/src/http/router/http.router.helpers.ts
packages/core/src/http/server/http.server.metadata.storage.ts
packages/core/src/http/server/http.server.tokens.ts
packages/core/src/http/server/http.server.ts
packages/core/src/http/server/specs/http.server.metadata.storage.spec.ts
packages/core/src/index.ts

```
[ ] Bugfix
[x] Feature
```
- **@marblejs/core** - throw `HttpRequestError` if dedicated `HttpError` is not thrown
- **@marblejs/core** - tests for `httpRequestMetadataStorage`
- **@integration** - style improvements for app boostrap methods
```
[ ] Yes
[x] No
```

feat(core): HttpRequestError

---

codecov.yml
packages/core/src/http/error/http.error.effect.ts
packages/core/src/http/router/http.router.resolver.v2.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

imp(core): detect and map HttpRequestError

---

packages/@integration/src/http/effects/api.effects.ts
packages/@integration/src/http/effects/event.effect.ts
packages/@integration/src/http/event.listener.ts
packages/@integration/src/http/index.ts
packages/@integration/src/messaging/client.ts
packages/@integration/src/messaging/server.ts
packages/@integration/src/websockets/websockets.server.ts
packages/core/src/http/router/http.router.resolver.v2.ts
packages/core/src/logger/logger.ts
packages/messaging/src/client/messaging.client.ts
packages/messaging/src/eventbus/messaging.eventBus.reader.ts
packages/messaging/src/index.ts
packages/messaging/src/server/messaging.server.listener.ts
packages/messaging/src/server/specs/messaging.server.amqp.spec.ts
packages/messaging/src/transport/strategies/amqp.strategy.ts
packages/messaging/src/transport/strategies/local.strategy.interface.ts
packages/messaging/src/transport/strategies/local.strategy.provider.ts
packages/messaging/src/transport/strategies/local.strategy.ts
packages/messaging/src/transport/strategies/redis.strategy.ts
packages/messaging/src/transport/strategies/tcp.strategy.interface.ts
packages/messaging/src/transport/transport.interface.ts
packages/messaging/src/transport/transport.provider.ts
packages/websockets/src/server/specs/websocket.server.spec.ts
packages/websockets/src/server/websocket.server.listener.ts

```
[ ] Bugfix
[x] Feature
```
- **@marblejs/messaging** - added `Local` TransportLayer strategy
```
[ ] Yes
[x] No
```

feat(messaging): EventBus

---

packages/core/src/logger/logger.interface.ts
packages/core/src/logger/logger.ts
packages/messaging/src/middlewares/messaging.eventLogger.middleware.ts
packages/websockets/src/middlewares/websockets.eventLogger.middleware.ts

```
[x] Bugfix
[ ] Feature
```
- **@marblejs/core,messaging,websockets** - corrected logs formatting for undefined values
```
[ ] Yes
[x] No
```

fix(core, messaging, websockets): corrected logs formatting for undefined values

---

packages/@integration/src/cqrs/effects/eventbus.effects.ts
packages/@integration/src/messaging/server.ts
packages/messaging/src/effects/messaging.effects.helper.ts
packages/messaging/src/effects/specs/messaging.effects.helper.spec.ts
packages/messaging/src/index.ts

```
[ ] Bugfix
[x] Feature
```
- **@marblejs/messaging** - `reply` utility function for routing outgoing event
```typescript
const effect$: MsgEffect = event$ => {
return event$.pipe(
matchEvent('TEST'),
mergeMap(event => of(event).pipe(
delay(10 * 1000),
mapTo(reply(event)({ type: 'TIMEOUT_RESULT' })),
)),
);
};
```
```
[ ] Yes
[x] No
```

feat(messaging): #reply utiltiy function

---

packages/core/src/http/effects/http.effects.ts
packages/core/src/http/server/http.server.event.subscriber.ts
packages/core/src/http/server/http.server.interface.ts
packages/core/src/http/server/http.server.ts
packages/core/src/http/server/specs/http.server.factory.spec.ts
yarn.lock

```
[x] Bugfix
[ ] Feature
```
Issue Number: #175
- **@marblejs/core** - added default HttpServer event effects for status logging
- **@marblejs/core** - resolved issue #175
```
[ ] Yes
[x] No
```

feat(core): added default HttpServer event effects for status logging

---

packages/middleware-multipart/src/multipart.parser.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor(middleware-multipart): busboy event handling

---

packages/@integration/src/http/effects/user.effects.ts
packages/@integration/src/http/fakes/random.ts
packages/core/src/http/router/http.router.combiner.ts
packages/core/src/http/router/http.router.helpers.ts
packages/core/src/http/router/http.router.interface.ts
packages/core/src/http/router/http.router.resolver.v2.ts

```
[x] Bugfix
[ ] Feature
```
- **@marblejs/core** - resolved an issue with already processing HttpRequest's that don't complete because of resubscribed stream caused by error
```
[ ] Yes
[x] No
```

fix(core): fixed an issue with resubscribed route stream in case of error

---

packages/core/src/http/effects/http.effects.factory.ts

```
[ ] Bugfix
[x] Feature
```
- **@marblejs/core** - deprecated `EffectFactory` route builder in favor of `r.pipe`
```
[ ] Yes
[ ] No
```

feat(core): deprecated `EffectFactory` builder

---

packages/@integration/package.json
packages/core/package.json
packages/messaging/package.json
packages/middleware-body/package.json
packages/middleware-cors/package.json
packages/middleware-io/package.json
packages/middleware-joi/package.json
packages/middleware-jwt/package.json
packages/middleware-logger/package.json
packages/middleware-multipart/package.json
packages/websockets/package.json

```
[ ] Bugfix
[x] Feature
```
- **@marblejs/all** - added `fp-ts` as a required peerDependecy
```
[x] Yes
[ ] No
```

feat: `fp-ts` as a peerDependency

---

packages/core/src/http/router/http.router.factory.ts

```
[ ] Bugfix
[x] Feature
```
- **@marblejs/core** - In case the route redefinition is found `factorizeRouting` function will throw a `CoreError` instead of default `Error`
```
[ ] Yes
[x] No
```

feat(core): route redefinition error improvement

---

packages/core/src/+internal/testing/http.helper.ts
packages/core/src/+internal/testing/metadata.helper.ts
packages/core/src/+internal/utils/error.util.ts
packages/core/src/+internal/utils/http.util.ts
packages/core/src/+internal/utils/spec/any.util.spec.ts
packages/core/src/+internal/utils/spec/array.util.spec.ts
packages/core/src/+internal/utils/spec/error.util.spec.ts
packages/core/src/+internal/utils/spec/http.util.spec.ts
packages/core/src/+internal/utils/spec/string.util.spec.ts
packages/core/src/+internal/utils/string.util.ts
packages/core/src/http/router/specs/http.router.resolver.v2.spec.ts

```
[ ] Bugfix
[ ] Feature
[x] Tests
```
```
[ ] Yes
[x] No
```

test(core): #resolveRouting - concurrent requests

---

packages/core/src/+internal/utils/any.util.ts
packages/messaging/src/eventbus/messaging.eventBus.reader.spec.ts
packages/messaging/src/eventbus/messaging.eventBus.reader.ts
packages/messaging/src/server/specs/messaging.server.amqp.spec.ts
packages/messaging/src/server/specs/messaging.server.redis.spec.ts
packages/messaging/src/util/messaging.test.util.ts

```
[ ] Bugfix
[ ] Feature
[x] Other...
```
```
[ ] Yes
[x] No
```

test(messaging): eventBus

---

packages/core/src/+internal/utils/error.util.ts
packages/core/src/+internal/utils/spec/string.util.spec.ts
packages/core/src/error/error.model.ts
packages/core/src/http/error/http.error.model.ts
packages/core/src/operators/act/act.operator.spec.ts
packages/core/src/operators/act/act.operator.ts
packages/messaging/src/client/messaging.client.spec.ts
packages/messaging/src/client/messaging.client.ts
packages/messaging/src/effects/messaging.effects.helper.ts
packages/messaging/src/eventbus/messaging.eventBus.reader.spec.ts
packages/messaging/src/transport/transport.error.ts
packages/messaging/src/util/messaging.test.util.ts
packages/middleware-io/src/io.error.ts
packages/websockets/src/error/websocket.error.model.ts

```
[ ] Bugfix
[x] Feature
```
- **@marblejs/core** - `act.operator` pass event metadata in default error mapper
- **@marblejs/messaging** - `messagingClient` -  detect error event response and throw exception
```
[ ] Yes
[x] No
```

feat(messaging): messagingClient - detect error event response and throw exception

---

packages/messaging/src/client/messaging.client.interface.ts
packages/messaging/src/client/messaging.client.ts

```
[x] Bugfix
[ ] Feature
```
- **@marblejs/messaging** - corrected `messagingClient.send` type inference for output events
```
[ ] Yes
[x] No
```

fix(messaging): messagingClient.send output type inference

---

packages/messaging/src/client/messaging.client.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(messaging): defer messaging client `send` call

---

packages/core/package.json
packages/core/src/+internal/utils/string.util.ts
packages/core/src/context/context.token.factory.ts
packages/messaging/src/util/messaging.test.util.ts
yarn.lock

Compatibility with uuid@7
```
[x] Bugfix
[ ] Feature
```
Issue Number: #241 
```
[ ] Yes
[x] No
```
I've updated the uuid deps to 7, built and ran tests successfully - also tested against original uuid 3.4.0 version - that's ok with these changes too.
I've left the uuid version at 7 in this PR, but you can switch back to 3.4.0 if you'd prefer.

fix(all): update to uuid@7

---

packages/core/src/operators/act/act.operator.ts
packages/messaging/src/client/messaging.client.interface.ts
packages/messaging/src/client/messaging.client.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(sa-so-gateway): act.operator error type mapping

---

packages/messaging/src/client/messaging.client.spec.ts
packages/messaging/src/util/messaging.test.util.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

test(messaging): Redis client

---

packages/core/src/http/error/http.error.model.ts

```
[x] Bugfix
[ ] Feature
```
- HTTP module throws an unhandled error (crashes an already running app) if thrown error is `undefined`
- HTTP server won't crash if thrown error is `undefined`
```
[ ] Yes
[x] No
```

fix(core): isHttpError + isHttpRequestError checks for undefined error

---

packages/@integration/package.json
packages/@integration/src/messaging/client.ts
packages/@integration/src/messaging/server.ts
packages/@integration/test/messaging.integration.spec.ts
packages/messaging/src/transport/strategies/redis.strategy.helper.ts
packages/messaging/src/transport/strategies/redis.strategy.ts

```
[x] Bugfix
[ ] Feature
```
- **@marblejs/messaging** - `redis` - RPC communication registers unnecessary `message` event handlers each time `send` method is called
- **@marblejs/messaging** - `redis` - **connect** event is not triggered when server started
- **@marblejs/messaging** - `redis` - only one `message` event handler defined for RPC calls
- **@marblejs/messaging** - `redis` - added missing **connect** event on startup
```
[ ] Yes
[x] No
```

fix(messaging): redis RPC communication

---

packages/core/src/context/context.factory.helper.ts
packages/core/src/context/context.logger.ts
packages/core/src/context/specs/context.factory.helper.spec.ts
packages/core/src/http/server/http.server.ts
packages/core/src/index.ts
packages/messaging/src/server/messaging.server.ts
packages/websockets/src/server/websocket.server.ts

```
[ ] Bugfix
[x] Feature
```
- **@marblejs/core** - added helper function for building `Context`:
```typescript
const token1 = createContextToken<string>();
const token2 = createContextToken<string>();
const dependency1 = createReader(_ => 'test_1');
const dependency2 = createReader(_ => 'test_2');
const context = await contextFactory(
bindTo(token1)(dependency1),
bindTo(token2)(dependency2),
);
```
```
[ ] Yes
[x] No
```

feat(core): contextFactory

---

packages/testing/README.md
packages/testing/package.json
packages/testing/tsconfig.json

```
[ ] Bugfix
[ ] Feature
[x] Other
```
```
[ ] Yes
[x] No
```

chore(testing): module boilerplate

---

packages/core/src/+internal/utils/http.util.ts
packages/core/src/+internal/utils/index.ts
packages/core/src/+internal/utils/spec/http.util.spec.ts
packages/core/src/+internal/utils/type.util.ts
packages/testing/README.md
packages/testing/src/index.spec.ts
packages/testing/src/index.ts
packages/testing/src/testBed/http/http.testBed.interface.ts
packages/testing/src/testBed/http/http.testBed.request.interface.ts
packages/testing/src/testBed/http/http.testBed.request.spec.ts
packages/testing/src/testBed/http/http.testBed.request.ts
packages/testing/src/testBed/http/http.testBed.response.interface.ts
packages/testing/src/testBed/http/http.testBed.response.ts
packages/testing/src/testBed/http/http.testBed.spec.ts
packages/testing/src/testBed/http/http.testBed.ts
packages/testing/src/testBed/http/http.testBed.util.ts
packages/testing/src/testBed/testBed.interface.ts
packages/testing/src/testBed/testBedContainer.interface.ts
packages/testing/src/testBed/testBedContainer.spec.ts
packages/testing/src/testBed/testBedContainer.ts
packages/testing/src/testBed/testBedSetup.interface.ts
packages/testing/src/testBed/testBedSetup.spec.ts
packages/testing/src/testBed/testBedSetup.ts

```
[ ] Bugfix
[x] Feature
```
**@marblejs/testing** - HTTP test bed with corresponding TestBed setup utility functions
```
[ ] Yes
[x] No
```

feat(testing): http TestBed module

---

packages/@integration/package.json
packages/@integration/src/http/index.ts
packages/@integration/test/http.integration.spec.ts
packages/core/src/+internal/testing/http.helper.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor(integration): http - integration tests with @marblejs/testing

---

packages/messaging/package.json
packages/messaging/src/transport/strategies/amqp.strategy.ts
yarn.lock

```
[x] Bugfix
[ ] Feature
```
- **@marblejs/messaging** - when messaging TransportLayer is trying to close a not yet connected channel the transport layer crashes
- **@marblejs/messaging** - transport layer waits till connected and then tries to close the connection
```
[ ] Yes
[x] No
```

fix(messaging): wait till transport layer connected and try to close connection

---

packages/@integration/src/http/index.ts
packages/@integration/src/messaging/client.ts
packages/@integration/test/http.integration.spec.ts
packages/@integration/test/messaging.integration.spec.ts
packages/testing/src/testBed/testBedContainer.spec.ts
packages/testing/src/testBed/testBedSetup.interface.ts
packages/testing/src/testBed/testBedSetup.spec.ts
packages/testing/src/testBed/testBedSetup.ts

```
[ ] Bugfix
[x] Feature
```
- **@marblejs/testing** - removed early `testBedSetup` context resolving to avoid hanging connections
```
[ ] Yes
[x] No
```

feat(testing): removed early testBedSetup context resolving

---

packages/@integration/src/cqrs/index.ts
packages/@integration/src/websockets/http.server.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor(integration): cqrs and websockets server bootstrapping

---

packages/core/src/+internal/utils/http.util.ts
packages/testing/src/testBed/testBed.interface.ts
packages/testing/src/testBed/testBedContainer.interface.ts
packages/testing/src/testBed/testBedContainer.ts
packages/testing/src/testBed/testBedSetup.interface.ts
packages/testing/src/testBed/testBedSetup.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor(testing): testBedSetup + testBedSetupContainer

---

packages/messaging/src/transport/strategies/amqp.strategy.ts

```
[x] Bugfix
[ ] Feature
```
- **@marblejs/messaging** - AMQP strategy connection event is not triggered on initial connection
```
[ ] Yes
[x] No
```

fix(messaging): AMQP strategy doesn't trigger initial connection event

---

packages/messaging/src/server/specs/messaging.server.amqp.spec.ts
packages/messaging/src/transport/strategies/amqp.strategy.ts

```
[x] Bugfix
[ ] Feature
```
- **@marblejs/messaging** - when microservice is not yet fully bootstrapped and there are some hanging messages on the queue, the AMQP strategy starts consuming them too early - before the effects are fully subscribed to incoming message stream
- **@marblejs/messaging** - AMQP strategy consumes correctly messages after the full startup - no lost messages anymore
```
[ ] Yes
[x] No
```

fix(messaging): messages are consumed before full startup

---

.eslintrc.js
package.json
packages/@integration/src/cqrs/domain/Offer.command.ts
packages/@integration/src/cqrs/domain/Offer.event.ts
packages/core/src/+internal/utils/array.util.ts
packages/core/src/error/error.model.ts
packages/core/src/event/event.factory.ts
packages/core/src/http/error/http.error.model.ts
packages/core/src/http/server/http.server.listener.ts
packages/core/src/logger/logger.interface.ts
packages/messaging/src/transport/strategies/amqp.strategy.interface.ts
packages/middleware-body/src/body.model.ts
packages/middleware-io/src/io.error.ts
packages/middleware-jwt/src/jwt.factory.ts
packages/middleware-jwt/src/jwt.middleware.ts
packages/middleware-multipart/src/multipart.interface.ts
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
- TypeScript v3.9 support
- updated `ts-jest` to v26.1.0
- corrected `ts-lint` warnings
```
[ ] Yes
[x] No
```

chore: typescript v3.9 support

---

packages/messaging/src/transport/strategies/amqp.strategy.ts

```
[x] Bugfix
[ ] Feature
```
- **@marblej/messaging** - when `disconnect` event occurs there is no error log propagated in the `error$`
```
[ ] Yes
[x] No
```

fix(messaging): amqp strategy - `disconnect` event

---

package.json
packages/core/src/event/event.spec.ts
packages/core/src/event/event.ts
packages/middleware-io/package.json
packages/middleware-io/src/io.event.middleware.ts
packages/middleware-io/src/specs/io.event.middleware.spec.ts
yarn.lock

```
[x] Bugfix
[x] Feature
```
- **@marblejs/core** - `#event` - added missing `io-ts` types
- **@marblejs/middleware-io** - `eventValidator$` - added support for Event codec type inference
```
[ ] Yes
[x] No
```

feat(middleware-io): eventValidator$ - added support for Event codec

---

packages/core/src/event/event.ts
packages/core/src/operators/matchEvent/matchEvent.operator.ts
packages/middleware-io/src/io.event.middleware.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(core): `matchEvent` - match event codec by literal value instead of by codec `.is` method

---

packages/@integration/src/messaging/server.ts
packages/@integration/src/websockets/websockets.server.ts
packages/messaging/src/eventbus/messaging.eventBus.reader.spec.ts
packages/messaging/src/server/specs/messaging.server.amqp.spec.ts
packages/messaging/src/server/specs/messaging.server.redis.spec.ts
packages/middleware-io/src/io.event.middleware.ts
packages/middleware-io/src/specs/io.event.middleware.spec.ts

```
[ ] Bugfix
[x] Feature
```
- **@marblejs/middleware-io** -  allow to pass single event to middleware
```
[ ] Yes
[x] No
```

feat(middleware-io): allow to pass single event to middleware

---

packages/messaging/src/middlewares/messaging.ack.middleware.ts
packages/messaging/src/transport/transport.transformer.spec.ts
packages/messaging/src/transport/transport.transformer.ts

```
[x] Bugfix
[x] Feature
```
- *@marblejs/messaging** - `decodeMessage` - pass metadata from raw message if event is UNKNOWN
- *@marblejs/messaging** - `rejectUnhandled$` - better inform which event is rejected
```
[ ] Yes
[x] No
```

fix(messaging): decodeMessage - pass metadata from raw message if event is UNKNOWN

---

packages/messaging/src/eventbus/messaging.eventBus.reader.ts
packages/messaging/src/transport/strategies/local.strategy.provider.ts
packages/messaging/src/transport/transport.provider.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(messaging): allow to pass `timeout` option to EventBus config

---

packages/core/src/context/context.helper.ts
packages/core/src/context/specs/context.helper.spec.ts
packages/core/src/event/event.interface.ts
packages/messaging/src/eventbus/messaging.eventBus.reader.ts
packages/messaging/src/middlewares/messaging.eventLogger.middleware.spec.ts
packages/messaging/src/middlewares/messaging.eventLogger.middleware.ts
packages/messaging/src/server/messaging.server.listener.ts

```
[x] Bugfix
[x] Feature
```
- **@marblejs/messaging** - `contextFactory` registers default `LoggerToken` if derived context doesn't have it bound
- **@marblejs/messaging** - `eventBus` - expose resolved `Context`
- **@marblejs/messaging** - `outputLogger$` - outputs detailed logs for event validation errors
- **@marblejs/messaging** - refactored event logger middleware
```
[ ] Yes
[x] No
```

feat(messaging): detailed logs for event validation errors

---

package.json
packages/@integration/package.json
packages/middleware-io/package.json
packages/middleware-io/src/io.middleware.ts
packages/middleware-io/src/io.request.middleware.ts
packages/middleware-io/src/specs/io.middleware.spec.ts
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
- Support for TypeScript v4.0.x
- Updated related packages
- **@marblejs/middleware-io** - refactored and adjusted io validator middleware to support TS v4.0
```
[ ] Yes
[x] No
```

build: typescript v4.0 support

---

packages/core/src/+internal/testing/http.helper.ts
packages/core/src/http/router/http.router.resolver.v2.ts
packages/core/src/http/server/http.server.listener.ts
packages/core/src/http/server/http.server.spec.ts
packages/core/src/http/server/http.server.tokens.ts
packages/core/src/http/server/http.server.ts
packages/core/src/http/server/internal-dependencies/httpRequestBus.reader.ts
packages/core/src/http/server/internal-dependencies/httpServerClient.reader.ts
packages/core/src/index.spec.ts
packages/core/src/index.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor(core): HttpServer internal dependencies

---

packages/core/src/+internal/utils/spec/string.util.spec.ts
packages/core/src/+internal/utils/string.util.ts
packages/messaging/src/server/messaging.server.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(messaging): mask microservice URI authorization component in logs

---

packages/middleware-body/package.json
packages/middleware-body/src/body.middleware.ts
packages/middleware-body/src/body.util.ts
packages/middleware-body/src/parsers/default.body.parser.ts
packages/middleware-body/src/parsers/json.body.parser.ts
packages/middleware-body/src/parsers/text.body.parser.ts
packages/middleware-body/src/parsers/url.body.parser.ts
packages/middleware-body/src/specs/body.middleware.spec.ts
yarn.lock

```
[x] Bugfix
[ ] Feature
```
Issue Number: #299
- **@marblejs/middleware-body** - content type charset parameters, eg. `Content-Type: text/plain;charset=utf-8` are properly supported
```
[ ] Yes
[x] No
```

fix(middleware-body): proper content-type charset support

---

packages/messaging/src/transport/strategies/amqp.strategy.ts

```
[x] Bugfix
[ ] Feature
```
- **@marblejs/messaging** - AQMP strategy - messaging client reconnection results in RPC queues high spike
```
[ ] Yes
[x] No
```

fix(messaging): high spike of RPC queues for AMQP strategy

---

packages/middleware-io/src/io.json-schema.ts
packages/middleware-io/src/specs/io.json-schema.spec.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(middleware-io): don't throw an error if unknown tag was found

---

README.md
packages/@integration/tsconfig.json
packages/core/README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

chore: removed deprecated middlewares leftovers

---

packages/messaging/src/transport/strategies/amqp.strategy.ts
packages/messaging/src/transport/strategies/local.strategy.ts
packages/messaging/src/transport/strategies/redis.strategy.ts
packages/websockets/src/server/websocket.server.listener.ts
packages/websockets/src/server/websocket.server.response.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor: firstValueFrom -> lastValueFrom

---

packages/core/src/+internal/utils/any.util.ts
packages/http/src/+internal/contentType.util.spec.ts
packages/http/src/+internal/contentType.util.ts
packages/http/src/response/http.responseBody.factory.ts
packages/middleware-body/src/body.util.ts
packages/middleware-body/src/parsers/default.body.parser.ts
packages/middleware-body/test/bodyParser.integration.ts
packages/middleware-multipart/src/multipart.util.ts
packages/testing/src/testBed/http/http.testBed.response.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor(http): content type utility functions

---

packages/core/src/+internal/utils/any.util.ts
packages/http/src/+internal/testing.util.ts
packages/http/src/http.interface.ts
packages/http/src/response/http.responseBody.factory.ts
packages/http/src/response/http.responseHandler.ts
packages/http/src/response/http.responseHeaders.factory.ts
packages/http/src/response/specs/http.responseBody.factory.spec.ts
packages/http/src/response/specs/http.responseHandler.spec.ts
packages/http/src/response/specs/http.responseHeaders.factory.spec.ts
packages/http/src/server/http.server.listener.ts
packages/middleware-cors/src/middleware.ts
packages/middleware-cors/src/spec/middleware.spec.ts
packages/testing/src/testBed/http/http.testBed.ts

```
[ ] Bugfix
[ ] Feature
```
- **@marblejs/core** - `HttpResponse.send` method instead of an `Observable<never>` returns `Observable<boolean>`
```
[x] Yes
[] No
```

refactor(http): #responseHandler

---

packages/core/src/event/event.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(core): io-ts deprecation warnings

---

packages/core/src/context/context.ts
packages/websockets/src/server/websocket.server.response.ts

```
[ ] Bugfix
[x] Feature
```
- **@marblejs/websockets** - lazy evaluation of `#emitEvent` and `#broadcastEvent` functions
```
[x] Yes
[ ] No
```

refactor(websockets): #broadcastEvent / #emitEvent

---

packages/core/src/+internal/utils/error.util.ts
packages/http/src/error/http.error.model.ts
packages/http/src/router/http.router.resolver.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor(http): moved #getErrorMessage to `@marblejs/core` module

---

.husky/commit-msg
.husky/pre-commit
package.json
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
- support for `husky` v7
```
[ ] Yes
[x] No
```

build: support for husky v7

---

.github/CONTRIBUTING.md

```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
```
[ ] Yes
[x] No
```

docs: updated CONTRIBUTING.md

---

packages/messaging/src/eventbus/messaging.eventBus.reader.ts

The reference to EventBusClient should be EventBus
What kind of change does this PR introduce? Minor documentation change.
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
```
[ ] Yes
[X] No
```

docs(messaging): fix deprecation message

---

packages/core/src/context/specs/context.spec.ts

```
[ ] Bugfix
[ ] Feature
[x] Test cases
```
```
[ ] Yes
[x] No
```

test(core): additional test cases for context resolving
