- packages/core/src/http.listener.spec.ts
- packages/core/src/operators/use.operator.spec.ts
- packages/core/src/operators/use.operator.ts
- Added `use` operator for composing custom middlewares inside *Effect* request pipeline
- Added + updated test cases for new feature
Using `use` operator we can compose custom middlewares inside our *Effect* pipeline. For example we can use it for authorization purposes, eg. like this:
**auth.middleware.ts**
```javascript
export const authorize$: Effect<HttpRequest> = request$ => request$
.pipe(
tap(req => {
if (!isAuthorized(req)) {
throw new HttpError('Unauthorized', HttpStatus.UNAUTHORIZED);
}
})
);
```
**user.controller.ts**
```javascript
const getUsers$: Effect = request$ => request$
.pipe(
matchPath('/'),
matchType('GET'),
use(authorize$),
...
);
```
> feature - compose middlewares inside Effect pipeline

- packages/core/package-lock.json
- packages/core/src/http.interface.ts
- packages/core/src/http.listener.spec.ts
- packages/core/src/operators/matchPath.operator.spec.ts
- packages/core/src/operators/matchPath.operator.ts
In the operator `matchPath` added information about the route:
* `path`
* `params`
Now, in `matchPath` operator you can add after sign `:` also parameters. Example: `matchPath('/foo/:id/:name?'),`
In the results, you receive the request object with information about parameters. 
* `/:id` - parameter
* `/:name?` - optional parameter
> feature - intercepting url parameters

- packages/core/src/http.listener.ts
I'm not sure of this correction at all but it seems that otherwise when there are two almost concurrent (and long) requests the second cancels the first one. (switchMap vs flatMap).
```
[X] Bugfix
[ ] Feature
```
When there are two long requests at the same time on the same path. The second cancel the first one. The browser won't receive any response for the first request. Only the second is successful.
Both browser pages seems to receive the response
```
[X] I don't know
```
> fix(core): Allow parrallel requests to work.

- docs/assets/index.html
- package-lock.json
- package.json
- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/effects/effects.combiner.spec.ts
- packages/core/src/http.listener.ts
- packages/core/src/middlewares/error.middleware.spec.ts
- packages/core/src/operators/matchPath/matchPath.operator.spec.ts
- packages/core/src/operators/matchType/matchType.operator.spec.ts
- packages/core/src/operators/use/use.operator.spec.ts
- packages/core/src/response/response.handler.spec.ts
- packages/core/src/response/response.handler.ts
- packages/core/src/response/responseBody.factory.spec.ts
- packages/core/src/response/responseBody.factory.ts
- packages/core/src/response/responseContentType.factory.spec.ts
- packages/core/src/response/responseContentType.factory.ts
- packages/core/src/response/responseHeaders.factory.spec.ts
- packages/core/src/response/responseHeaders.factory.ts
- packages/core/src/util/contentType.util.ts
- packages/middleware-body/src/indes.spec.ts
- packages/middleware-logger/src/index.spec.ts
- packages/spec/api.integration.spec.ts
- packages/util/fileReader.helper.spec.ts
- packages/util/fileReader.helper.ts
- packages/util/marbles.spec-util.ts
```
[x] Bugfix
[x] Feature
[x] Tests
```
- When trying to serve static files, `responseHandler` tries to `JSON.stringify()` every outgoing response.
- `responseHandler` doesn't detect mime-types automatically
Issue Number: #33 
- stream based `fileReader`
- integration tests for serving static files
- auto set response `content-type` based on provided body
- moved `marbles.spec-util` to common `util` folder
- added `mock-fs`, `mime` and `file-type` packages
```
[ ] Yes
[x] No
```
> feat(core): handle response content types

- packages/core/src/effects/effects.combiner.ts
- packages/core/src/http.interface.ts
- packages/core/src/operators/matchPath/matchPath.operator.spec.ts
- packages/core/src/operators/matchPath/matchPath.operator.ts
- packages/core/src/operators/matchType/matchType.operator.spec.ts
- packages/core/src/operators/matchType/matchType.operator.ts
- packages/spec/routing.integration.spec.ts
```
[x] Bugfix
[x] Feature
[x] Tests
```
For two effects defined:
- `/user/search`
- `/user/:id`
Both effects got applied, resulting in:
`Error: Can't set headers after they are sent.`
Issue Number: #35, #27  
- _Effects_ are matched one by one
- only one _Effect_ should be resolved
- match all paths using `*` sign
```
[ ] Yes
[x] No
```
> fix(core): Effect matching hazard

- example/src/controllers/api.controller.ts
- packages/core/src/operators/matchType/matchType.operator.spec.ts
- packages/core/src/operators/matchType/matchType.operator.ts
```
[ ] Bugfix
[x] Feature
[x] Documentation content changes
```
- it is impossible to implement `404` handler because `matchType` can't match all http types
Issue Number: #27 
- `matchType` can have as an argument `*` sign - which means: "match all method types"
```
[ ] Yes
[x] No
```
> feat(core): matchType - match all types using * sign

- packages/middleware-logger/src/index.ts
- packages/middleware-logger/src/time.factory.spec.ts
- packages/middleware-logger/src/time.factory.ts
```
[x] Bugfix
[ ] Feature
```
- `@marblejs/middleware-logger` displays wrong response times
- `@marblejs/middleware-logger` displays proper response times
```
[ ] Yes
[x] No
```
> fix(logger): display proper response time

- packages/core/src/effects/effects.combiner.spec.ts
- packages/core/src/effects/effects.combiner.ts
- packages/core/src/effects/effects.helpers.spec.ts
- packages/core/src/effects/effects.helpers.ts
- packages/core/src/effects/effects.interface.ts
```
[ ] Bugfix
[x] Feature
```
It is impossible to compose middlewares on combined routes via `combineRoute()` method
Issue Number: #36 
This feature introduces and enhancement to `combineRoutes()` method which allows to compose middlewares for grouped routes.
```javascript
combineRoutes('/api', {
middlewares: [ someMiddleware$ ],
effects: [ someEffect$ ]
});
```
In order to keep backward compatibility, we can call `combineRoutes()` without object config, like we used to do before:
```javascript
combineRoutes('/api', [ …
```
> feat(core): use middlewares with `combinedRoutes`

- package-lock.json
- packages/core/src/util/contentType.util.ts
- packages/middleware-body/src/indes.spec.ts
- packages/middleware-body/src/index.ts
- packages/middleware-body/src/urlEncoded.serializer.spec.ts
- packages/middleware-body/src/urlEncoded.serializer.ts
```
[ ] Bugfix
[x] Feature
```
Currently `bodyParser` don't support `x-www-form-urlencoded` body.
In the new behavior, we can use `x-www-form-urlencoded` body for `POST`, `PUT` and `PATCH` methods. For example when we send `x-www-form-urlencoded` data:
```
test=test&test-2=test-2&test-3=3
```
In the result we can receive object: 
```
{
test: 'test',
'test-2': 'test-2',
'test-3': 3,
}
```
```
[ ] Yes
[x] No
```
> feat(middleware-body): support for x-www-form-urlencoded

- example/src/controllers/user.controller.ts
- package-lock.json
- packages/core/src/effects/effects.combiner.ts
- packages/core/src/http.interface.ts
- packages/core/src/http.listener.spec.ts
- packages/core/src/http.listener.ts
- packages/core/src/response/response.handler.spec.ts
- packages/core/src/response/response.handler.ts
- packages/core/src/router/router.spec.ts
- packages/core/src/router/router.ts
```
[x] Bugfix
[x] Feature
```
- If middleware sends response before reaching to designated _Effect_ the server crashes with the following error: `Can't render headers after they are sent to the client.`
- If middleware wants to send response before reaching to designated _Effect_, developer needs to send response via default Node.JS `http.OutgoingMessage` API.
- Added dedicated guards inside request/response lifecycle flow to check if response was finished. 
- Exposed `handleResponse` method to be publicly visible as `req.send` …
> feat(core): expose `handleResponse` to public API

- packages/core/src/effects/effects.factory.ts
- packages/core/src/effects/specs/effects.factory.spec.ts
- packages/core/src/error/error.effect.ts
- packages/core/src/error/error.factory.ts
- packages/core/src/error/error.model.ts
- packages/core/src/error/specs/error.factory.spec.ts
- packages/core/src/error/specs/error.model.spec.ts
- packages/core/src/http.interface.ts
- packages/core/src/util/array.util.ts
```
[ ] Bugfix
[x] Feature
```
For non-TypeScript developers there is not any sort of validation made during app startup, eg. `EffectFactory` methods are not validated if developer will provide wrong `HttpMethod` to the `matchType` method.
Issue Number: https://github.com/marblejs/marble/projects/1#card-11043276
- refactored `EffectFactory` builder
- added validation for `EffectFactory` methods
- introduced dedicated `CoreError` error type used for throwing an package related error messages, eg. for notifying non-TypeScript …
> feat: `EffectFactory` validation + dedicated `CoreError` stack traces

- README.md
- jest.config.js
- packages/@integration/test/integration.spec.ts
- packages/core/package.json
- packages/core/src/+internal/fp/maybe.ts
- packages/core/src/+internal/fp/spec/compose.spec.ts
- packages/core/src/+internal/fp/spec/maybe.spec.ts
- packages/core/src/router/router.factory.ts
- packages/core/src/router/specs/router.factory.spec.ts
- packages/core/src/router/urlParams.factory.ts
- packages/middleware-body/package.json
- packages/middleware-joi/package.json
- packages/middleware-logger/package.json
```
[x] Bugfix
[ ] Feature
[x] Test cases
```
- `factorizeRouting()` incorrectly concatenates wildcard endpoint when combined with parametrized route, which results in the following concatenated string: `/api/:version*`.  See example below 👇 
```javascript
const notFound$ = EffectFactory
.matchPath('*')
.matchType('*')
.use(req$ => req$.pipe(
switchMap(() =>
throwError(new HttpError('Route not found', HttpStatus.NOT_FOUND))
)
));
export const api$ = combineRoutes(
'/api/:version',
[ notFound$ ],
);
```
- Added test cases for `compose` and `Maybe` monad
- …
> fix(core): fixed problem with path concatenation combined with wildcard sign

- packages/@integration/src/effects/user.effects.ts
- packages/@integration/src/fakes/dao.fake.ts
- packages/@integration/test/integration.spec.ts
- packages/core/src/router/router.ts
```
[x] Bugfix
[ ] Feature
```
Lets assume that we have the following effect definition with authorization middleware applied for route:
```typescript
const getUser$ = EffectFactory
.matchPath('/:id')
.matchType('GET')
.use(req$ => req$.pipe(
map(req => req.params.id),
switchMap(Dao.getUserById),
map(user => ({ body: user })),
catchError(() =>
throwError(new HttpError('User does not exists', HttpStatus.NOT_FOUND))
)
));
export const user$ = combineRoutes('/user', {
middlewares: [authorize$],
effects: [getUser$],
});
```
When the …
> fix(core): effect error catching from middleware thrown error

- packages/core/src/effects/effects.interface.ts
- packages/core/src/http.interface.ts
- packages/core/src/operators/use/use.operator.ts
```
[ ] Bugfix
[x] Feature
```
Composed middlewares by `use` operator don't infer and return proper `HttpRequest` type. When we will modify inner `Observable` with `map` the `use` operator doesn't infer the chained middleware types properly.
Issue Number: #78 
`HttpRequest` is properly inferred via composed middlewares.
```typescript
const middleware$: Middleware<TBody> = req$ => req$.pipe(
...
);
// or
const middleware$ = (req$: Observable<HttpRequest>) => req$.pipe(
map(req => req as HttpRequest<TBody>),
);
// then
const …
```
> feat(core): improved HttpRequest types inference for middlewares composition

- package.json
- packages/core/src/effects/effects.interface.ts
- packages/core/src/http.interface.ts
- packages/core/src/http.listener.ts
- packages/core/src/response/response.handler.ts
- packages/core/src/router/router.interface.ts
- packages/core/src/router/router.resolver.ts
- yarn.lock
```
[ ] Bugfix
[x] Feature
```
- `EffectResponse` interface is restricted only to HTTP protocol. It should be only represented as a base type which could be used outside, eg. in websockets protocol.
- The basic `Effect` generic interface extends `EffectResponse` defaulting to `EffectHttpResponse` type - because we are targeting HTTP protocol by default. From now it allows us to build Effects, not restricted only to HTTP protocol. 
```typescript
export interface EffectResponse<T = any> {
body?: T;
}
export interface …
```
> feat(core): introducing EffectHttpResponse type

- .gitignore
- jest.config.js
- packages/@integration/package.json
- packages/@integration/src/effects/api.effects.ts
- packages/@integration/src/effects/static.effects.ts
- packages/@integration/src/effects/user.effects.ts
- packages/@integration/src/fakes/dao.fake.ts
- packages/@integration/test/integration.spec.ts
- packages/core/src/http.interface.ts
- packages/core/src/operators/use/use.operator.spec.ts
- packages/core/src/operators/use/use.operator.ts
- packages/middleware-joi/package.json
- packages/middleware-joi/src/validator.interface.ts
- packages/middleware-joi/src/validator.middleware.ts
- tsconfig.json
- tsconfig.test.json
- yarn.lock
```
[ ] Bugfix
[x] Feature
```
- `@marblejs/core` - `use` operator can't properly infer combined, chained middlewares, like:
```typescript
const m1$: Middleware = req$ =>
req$.pipe(
tap(req => req.body = { test: 'test' }),
);
const m2$: Middleware = req$ =>
req$.pipe(
tap(req => req.params = { test: true }),
);
// then
const effect$: Effect = req$ =>
req$.pipe(
use(m1$),
use(m2$),
tap(req => req.body.test),    // body.test === "any"
tap(req => req.params.test),  // params.test === "any"
// ...
);
```
Issue Number: #78
- …
> imp(core, middleware-joi, @integration): improved type-inference of combined middlewares

- packages/@integration/src/effects/api.effects.ts
- packages/@integration/src/effects/calculator.ws-effects.ts
- packages/@integration/src/index.ts
- packages/core/src/effects/effects.combiner.ts
- packages/core/src/effects/effects.interface.ts
- packages/core/src/error/error.effect.ts
- packages/core/src/error/specs/error.effect.spec.ts
- packages/core/src/index.ts
- packages/core/src/listener/http.listener.ts
- packages/core/src/router/router.resolver.ts
- packages/core/src/router/specs/router.resolver.spec.ts
- packages/core/src/server/server.factory.ts
- packages/core/src/server/server.injector.ts
- packages/core/src/server/server.token.ts
- packages/core/src/server/specs/server.injector.spec.ts
- packages/middleware-body/src/index.spec.ts
- packages/middleware-io/test/io-ws.integration.spec.ts
- packages/middleware-joi/test/unit/body.spec.ts
- packages/middleware-jwt/src/spec/jwt.middleware.spec.ts
- packages/websockets/src/effects/ws-effects.interface.ts
- packages/websockets/src/error/specs/ws-error.effect.spec.ts
- packages/websockets/src/error/specs/ws-error.handler.spec.ts
- packages/websockets/src/error/ws-error.effect.ts
- packages/websockets/src/error/ws-error.handler.ts
- packages/websockets/src/listener/specs/websocket.listener.spec.ts
- packages/websockets/src/listener/websocket.listener.ts
- packages/websockets/src/operators/mapToServer/mapToServer.operator.spec.ts
- packages/websockets/src/operators/mapToServer/mapToServer.operator.ts
```
[ ] Bugfix
[ ] Feature
```
- In Marble.js v1 the third Effect argument (metadata) wasn't used often. The PR introduces a refactored way, where the third argument is a common `EffectMetadata` object which can contain eventual `error` object or contextual `injector`.
- Shareable injection container
- The `http.Server` instance is registered to the injection container during `httpListener` bootstrapping, it can be easily retrieved via container.
```
[x] Yes
[ ] No
```
> refactor(core): Effect metadata argument

- packages/core/src/+internal/testing/marbles.helper.ts
- packages/core/src/effects/effects.interface.ts
- packages/core/src/effects/effectsMetadata.factory.ts
- packages/core/src/index.ts
- packages/core/src/listener/http.listener.ts
- packages/core/src/router/specs/router.resolver.spec.ts
- packages/core/src/server/server.factory.ts
- packages/middleware-body/src/index.spec.ts
- packages/middleware-joi/test/unit/body.spec.ts
- packages/middleware-jwt/src/spec/jwt.middleware.spec.ts
- packages/websockets/src/error/specs/ws-error.handler.spec.ts
- packages/websockets/src/listener/websocket.listener.ts
```
[ ] Bugfix
[x] Feature
```
- `EffectMetadata` contains the RxJS Scheduler instance which can be handy for unit-testing Rx streams.
```
[ ] Yes
[x] No
```
> feat(core): EffectMetadata scheduler

- packages/core/src/effects/effects.interface.ts
- packages/core/src/http.interface.ts
- packages/core/src/listener/http.listener.ts
- packages/core/src/response/responseContentType.factory.ts
- packages/websockets/src/effects/ws-effects.interface.ts
- packages/websockets/src/listener/websocket.listener.ts
```
[ ] Bugfix
[x] Feature
```
> [...] response interceptor to modify certain type of responses for various reasons. Such as when Accept header is application/vnd.api+json, so maybe there is a stream of outgoing message which can be use to adjust the response accordingly. The API endpoint should worry only about resource being worked on. The exact data sent over wire or its representation is orthogonal to the API endpoint. Or in other case, when RouteEffect sends _404_ as a status code. It will be intercepted by common code that …
> feat(core, websockets): Effects output stream

- packages/core/src/+internal/http/contentType.util.ts
- packages/middleware-body/src/specs/body.middleware.spec.ts
```
[x] Bugfix
[ ] Feature
```
- `@marblejs/middleware-body` doesn't parse `application/x-www-form-urlencoded` body types
```
[ ] Yes
[x] No
```
> fix(middleware-body): application/x-www-form-urlencoded

- packages/@integration/test/integration.spec.ts
- packages/core/package.json
- packages/core/src/router/router.query.factory.ts
- packages/middleware-body/package.json
- packages/middleware-body/src/parsers/url.body.parser.ts
- packages/middleware-body/src/specs/body.middleware.spec.ts
- packages/middleware-body/test/bodyParser.integration.spec.ts
- yarn.lock
```
[x] Bugfix
[ ] Feature
```
- `@marblejs/core` - the query parser cannot parse complex URL encoded strings, like:
```
foo[bar1][baz]=test1'
foo[bar2][baz]=test2'
```
- `@marblejs/middlware-body` - URL parser incorectly decodes complex `application/x-www-form-urlencoded` strings like:
```
foo[bar1][baz]=test1'
foo[bar2][baz]=test2'
```
or 
```
foo=some=value&which&is=complex
```
- `@marblejs/core` - integration with `qs` library (a querystring parser with nesting support)
- `@marblejs/middlware-body` - ☝️
```
[ ] Yes
[x] No …
```
> fix(core, middleware-body): incorrectly parsed querystrings

- packages/core/src/context/context.factory.ts
- packages/core/src/context/specs/context.factory.spec.ts
```
[ ] Bugfix
[x] Feature
```
- context asked for lazy reader dependency returns a new instance every time
- context asked for lazy reader dependency returns a new instance only once, next time it will return previously bootstrapped instance
```
[ ] Yes
[x] No
```
> imp(core): ask context for lazy reader dependency and bootstrap it only once

- packages/core/src/index.ts
- packages/core/src/server/server.factory.ts
- packages/core/src/server/server.tokens.ts
```
[ ] Bugfix
[x] Feature
```
A developer has no access to propagated server events inside bound dependency.
`createServer` context bounds stream of HTTP server events to `serverEvent$` token.
eg. developer can subscribe for `ServerEvent.close` and react accordingly (eg. closing an opened connection).
```typescript
import { serverEvent$ } from '@marblejs/core';
...
ask(serverEvent$)
.map(event$ => event$.pipe(
matchEvent(ServerEvent.close),
take(1),
mergeMapTo(client.closeConnection())
))
.getOrElse(EMPTY)
.subscribe();
...
``` …
> feat(core): access server event stream via Context API

- packages/middleware-io/src/io.request.middleware.ts
- packages/middleware-io/src/specs/io.request.middleware.spec.ts
```
[x] Bugfix
[ ] Feature
```
`@marblejs/middleware-io` doesn't update validated values. So, after (successful) validation with `requestValidator$` we new static type but old unchanged value.
Issue Number: #131 
Let's say we have a codec that validates and decodes string values into numbers.
For example, we have a query parameter page `(?page=123)` that must be a number.
```typescript
const numberFromStringCodec = new t.Type<number, string, unknown>(
// ...    
);
// and we have GET /test?page=123
// the query input value will …
```
> fix(middleware-io): requestValidator$ updates decoded values

- packages/@integration/src/ws.listener.ts
- packages/websockets/src/effects/ws-effects.interface.ts
- packages/websockets/src/listener/specs/websocket.listener.spec.ts
- packages/websockets/src/listener/websocket.listener.ts
```
[x] Bugfix
[ ] Feature
```
- An incoming connection is validated **after** the initial WebSocket handshake.
- Incoming WebSocket connection is validated via `verifyClient` hook, just before initial handshake.
```
[ ] Yes
[x] No
```
> imp(websockets): use verifyClient for incoming connection verification

- packages/core/src/response/responseBody.factory.ts
```
[x] Bugfix
[ ] Feature
```
A stream body is being stringified when:
* `Content-Type` header is set explicitly to `application/json`
* `Content-Type` header is not specified (it defaults to case above)
It also causes a header conflict when `Transfer-Encoding` header is explicitly set to `chunked`, because body is not a stream which causes `Content-Length` header to be set.
Body is not stringified when it's a stream, regardless of `Content-Type` header.
```
[ ] Yes
[x] No
```
It fixes issue with …
> fix(stream-responses): Stream response is stringified if Content-Type is application/json

- packages/core/src/server/specs/server.factory.spec.ts
- packages/serverless/README.md
- packages/serverless/package.json
- packages/serverless/src/+awsLambda/awsLambda.middleware.ts
- packages/serverless/src/+awsLambda/awsLambda.types.ts
- packages/serverless/src/+awsLambda/awsLambdaHandler.ts
- packages/serverless/src/+awsLambda/awsLambdaProxy.options.ts
- packages/serverless/src/+awsLambda/awsLambdaProxy.ts
- packages/serverless/src/+awsLambda/index.ts
- packages/serverless/src/+awsLambda/spec/__snapshots__/awsLambda.spec.ts.snap
- packages/serverless/src/+awsLambda/spec/awsLambda.middleware.spec.ts
- packages/serverless/src/+awsLambda/spec/awsLambda.postContext.mock.json
- packages/serverless/src/+awsLambda/spec/awsLambda.postEvent.mock.json
- packages/serverless/src/+awsLambda/spec/awsLambda.setup.ts
- packages/serverless/src/+awsLambda/spec/awsLambda.spec.ts
- packages/serverless/src/+awsLambda/spec/awsLambdaProxy.spec.ts
- packages/serverless/src/handler.ts
- packages/serverless/src/index.ts
- packages/serverless/src/serverProxy.helpers.ts
- packages/serverless/src/serverProxy.ts
- packages/serverless/src/spec/serverProxy.helpers.spec.ts
- packages/serverless/tsconfig.json
- tsconfig.json
- yarn.lock
```
[ ] Bugfix
[x] Feature
```
Marble.js can be used only as a standalone server, which can be run locally or in Docker environment.
Marble.js app can be proxied with `@marblejs/serverless` like below:
```ts
import { createLambda, ProxyType } from '@marblejs/severless';
import httpListener from './httpListener';
export = createLambda({
app: httpListener, // Your app goes here
type: ProxyType.AWS, // Currently we support only AWS Lambda with API Gateway
proxyOptions: { // Optional configuration for specified ProxyType …
```
> feat(serverless): Support for AWS Lambda

- packages/core/src/+internal/testing/http.helper.ts
- packages/core/src/effects/specs/effects.combiner.spec.ts
- packages/core/src/error/specs/error.effect.spec.ts
- packages/core/src/operators/switchToProtocol/switchToProtocol.operator.spec.ts
- packages/middleware-body/src/specs/body.util.spec.ts
- packages/serverless/src/+awsLambda/spec/awsLambda.middleware.spec.ts
```
[ ] Bugfix
[x] Feature
```
You have to pass `url` whenever you use `createHttpRequest` function. The function is only used for testing purposes.
Internally in `createHttpRequest` function, the defaults are set in a bit better way. Also, it does accept empty/partial object and still falls back to the right default values.
```
[ ] Yes
[x] No
```
I also updated usages of the method in all tests.
> imp(http helper): simplified `createHttpRequest` function and it's usages

- packages/middleware-io/src/io.json-schema.ts
- packages/middleware-io/src/specs/io.json-schema.spec.ts
- packages/middleware-io/src/specs/io.request.middleware.spec.ts
```
[x] Bugfix
[ ] Feature
```
`@marblejs/middleware-io` generates JSON Schema 7, which is not fully supported by OpenAPI Specification 3. OAS/Swagger does not support `const`.
We use `enum` instead of `const`, which simply works. 😄 
```
[ ] Yes
[x] No
```
> fix(testing/doc-gen): Removed const in favor of enum

- packages/@integration/test/integration.spec.ts
- packages/core/src/response/response.handler.ts
- packages/core/src/router/specs/router.query.factory.spec.ts
```
[x] Bugfix
[ ] Feature
```
Server returns `500` status code when query parameters contains URL-like value
Issue Number: #145 
Server reacts correctly when an URL ends with `.whatever` (eg. user@email.com)
```
[ ] Yes
[x] No
```
> fix(core): request url parse error

- packages/middleware-multipart/src/multipart.parser.file.ts
- packages/middleware-multipart/src/multipart.parser.ts
```
[x] Bugfix
[ ] Feature
```
- the middleware stream is resolved too early when the `stream` handler is attached
- the middleware stream is resolved when all streams finish their work
```
[ ] Yes
[x] No
```
> fix(middleware-multipart): wait until whole stream is finished

- packages/middleware-multipart/src/multipart.parser.file.ts
```
[x] Bugfix
[ ] Feature
```
- When sending _multipart/form-data_ body using eg. `FormData` package, `Busboy` doesn't trigger **finish** event.
- The stream is properly finishing when the middleware has to deal with default `ReadableStream`. 
```
[ ] Yes
[x] No
```
> fix(middleware-multipart): stream.resume()

- packages/core/src/+internal/testing/marbles.helper.ts
- packages/core/src/effects/effects.interface.ts
- packages/core/src/effects/effectsMetadata.factory.ts
- packages/core/src/effects/http-effects.interface.ts
- packages/core/src/error/error.effect.ts
- packages/core/src/error/specs/error.effect.spec.ts
- packages/core/src/listener/http.listener.ts
- packages/core/src/operators/matchEvent/matchEvent.operator.spec.ts
- packages/messaging/src/effects/messaging.effects.interface.ts
- packages/messaging/src/server/messaging.server.listener.ts
- packages/messaging/src/server/messaging.server.spec.ts
- packages/websockets/src/effects/ws-effects.interface.ts
- packages/websockets/src/error/specs/ws-error.effect.spec.ts
- packages/websockets/src/error/ws-error.effect.ts
- packages/websockets/src/error/ws-error.handler.ts
```
[ ] Bugfix
[x] Feature
```
- When dealing with an error or incoming request in HTTP `output$`, developer had to use the attribute placed in the third effect argument.
`const effect = (req$, client, { initiator, error }) => ...`
- In the case of `ErrorEffect` the thrown error is passed to stream directly:
```typescript
const error$: HttpErrorEffect<HttpError> = req$ =>
req$.pipe(
map(({ req, error }) => {
// ...
}),
);
```
- In the case of `OutputEffect` the message initiator (eg. initial request) is passed …
> refactor(core, websockets, messaging): pass error to stream instead of metadata object

- packages/core/src/event/event.factory.ts
```
[x] Bugfix
[ ] Feature
```
```
return event$.pipe(
matchEvent(DocumentEvent.createDocument),
mergeMap(event => event.raw), // TypeError: Property 'raw' does not exist on type [...]
);
```
- `matchEvent` - matched Event type contains `raw` attribute
```
[ ] Yes
[x] No
```
> fix(core): matchEvent is not infering `Event.raw` attribute

- packages/@integration/src/messaging/server.ts
- packages/messaging/src/server/messaging.server.listener.ts
- packages/messaging/src/server/specs/messaging.server.amqp.spec.ts
```
[x] Bugfix
[ ] Feature
```
- When an unhandled error is thrown the internally subscribed `messaging.listener` stream is closed. It results in unhandled incoming messages.
- The internal messaging stream is automatically reconnecting when the stream is unexpectedly closed.
```
[ ] Yes
[x] No
```
> fix(messaging): don't crash internal messages stream when unhandled error occurs

- packages/core/src/router/router.factory.ts
- packages/core/src/router/specs/router.factory.spec.ts
```
[x] Bugfix
[ ] Feature
```
When the middleware is composed through `r.use` pipe function it is not properly reflected inside the built routing table, which results in the wrong middleware application.
```typescript
const effect$ = r.pipe(
r.matchPath('/test'),
r.matchType('GET'),
r.use(someMiddleware$),
r.useEffect(req$ => req$.pipe(
// ...
)),
);
```
```
[ ] Yes
[x] No
```
> fix(core): RouteEffect middlewares

- packages/core/src/context/context.reader.factory.ts
- packages/core/src/http/effects/http.effects.interface.ts
- packages/core/src/http/server/http.server.listener.ts
- packages/core/src/index.ts
- packages/core/src/listener/listener.factory.ts
- packages/core/src/listener/listener.interface.ts
- packages/messaging/src/server/messaging.server.listener.ts
```
[ ] Bugfix
[x] Feature
```
- **@marblejs/core**, **@marblejs/messaging** - Introducing uniform way for creating `Listener` functions 
- **@marblejs/core** - `HttpListenerConfig` - `effects` is not required anymore (it is defaulted to empty array inside)
- **@marblejs/core** - exposed `createReader` function in public API. From now you don't have to write the whole *fp-ts* boilerplate in order to define context reader function
```
[ ] Yes
[x] No
```
> refactor(core, messaging): uniform Listener interface

- packages/@integration/src/http/index.ts
- packages/@integration/src/messaging/client.ts
- packages/@integration/src/messaging/server.ts
- packages/@integration/src/websockets/http.server.ts
- packages/@integration/src/websockets/websockets.server.ts
- packages/core/src/+internal/testing/http.helper.ts
- packages/core/src/context/context.factory.ts
- packages/core/src/context/specs/context.factory.spec.ts
- packages/core/src/context/specs/context.hook.spec.ts
- packages/core/src/http/server/http.server.ts
- packages/core/src/http/server/specs/http.server.factory.spec.ts
- packages/core/src/http/server/specs/http.server.listener.spec.ts
- packages/core/src/index.ts
- packages/messaging/src/+internal/testing/messaging.testBed.ts
- packages/messaging/src/server/messaging.server.ts
- packages/messaging/src/util/messaging.test.util.ts
- packages/middleware-io/test/io-ws.integration.spec.ts
```
[ ] Bugfix
[x] Feature
```
- **@marblejs/core** - asynchronous dependency binding
The application start should be delayed until one or more asynchronous tasks are completed. For example, you may not want to start accepting requests until the connection with the database has been established.
The syntax for this is to use async/await with the for reader dependencies. The factory returns a Promise, and the factory function can await asynchronous tasks. Context container (including Marble app factory) will await resolution of …
> feat(core): async dependencies

- packages/middleware-cors/src/middleware.ts
- packages/middleware-cors/src/spec/middleware.spec.ts
```
[x] Bugfix
[ ] Feature
```
- **@marblejs/middleware-cors** - processes a stream of requests further even if the response is sent 
- **@marblejs/middleware-cors** - kill stream processing if the response is sent via returning EMPTY stream
```
[ ] Yes
[x] No
```
> fix(cors): return EMPTY stream if CORS request is handled

- packages/@integration/src/http/effects/static.effects.ts
- packages/@integration/src/http/effects/user.effects.ts
- packages/core/src/+internal/utils/array.util.ts
- packages/core/src/error/error.factory.ts
- packages/core/src/http/effects/http.effects.interface.ts
- packages/core/src/http/error/http.error.model.ts
- packages/core/src/http/router/http.router.combiner.ts
- packages/core/src/http/router/http.router.factory.ts
- packages/core/src/http/router/http.router.helpers.ts
- packages/core/src/http/router/http.router.interface.ts
- packages/core/src/http/router/http.router.ixbuilder.ts
- packages/core/src/http/router/http.router.matcher.ts
- packages/core/src/http/router/http.router.resolver.v2.ts
- packages/core/src/http/router/specs/http.router.factory.spec.ts
- packages/core/src/http/router/specs/http.router.resolver.v2.spec.ts
- packages/core/src/http/server/http.server.tokens.ts
- packages/core/src/http/server/specs/http.server.listener.spec.ts
- packages/core/src/index.ts
- packages/middleware-body/src/body.middleware.ts
- packages/middleware-io/src/io.request.middleware.ts
- packages/middleware-jwt/src/jwt.middleware.ts
- packages/middleware-multipart/src/multipart.middleware.ts
- packages/middleware-multipart/src/multipart.parser.ts
```
[x] Bugfix
[x] Feature
```
Issue Number: #206 
- **@marblejs/core** - rethink the way how HTTP request processing is made underhood of `@marblejs/core` package.
- **@marblejs/core** - propagate route metadata, applied by `r.applyMeta` function to app routing table
- **@marblejs/core** -initialize every route effect eagerly (only once) when the whole app is bootstraping
- **@marblejs/core** - introduced `continuous` metadata flag for dealing with continuous request streams, eg.
```typescript
const getUserBuffered$ = r.pipe( …
```
> feat(core): continuous HTTP stream

- packages/middleware-multipart/src/multipart.parser.field.ts
- packages/middleware-multipart/src/multipart.parser.file.ts
- packages/middleware-multipart/src/specs/multipart.middleware.spec.ts
```
[x] Bugfix
[ ] Feature
```
- **@marblejs/middleware-multipart** - middleware hangs if only file is sent or only field
Issue Number: #186 
```
[ ] Yes
[x] No
```
> fix(middleware-multipart): middleware hangs if only file is sent or only field

- packages/@integration/src/http/effects/user.effects.ts
- packages/core/src/http/router/http.router.ixbuilder.ts
- packages/core/src/http/router/specs/http.router.ixbuilder.spec.ts
```
[ ] Bugfix
[x] Feature
```
- **@marblejs/core** - This improvement allows to put metadata on top of route builder.
```typescript
const foo$ = r.pipe(
r.applyMeta({ continuous: true }),
r.matchPath('/'),
r.matchType('GET'),
r.useEffect(req$ => {
return req$.pipe(
// ...
);
}));
```
```
[ ] Yes
[x] No
```
> feat(core): allowed to put `r.applyMeta` on top of route builder

- packages/messaging/src/effects/messaging.effects.helper.ts
- packages/messaging/src/effects/specs/messaging.effects.helper.spec.ts
- packages/messaging/src/index.spec.ts
- packages/messaging/src/index.ts
```
[x] Bugfix
[ ] Feature
```
- **@marblejs/messaging** - `EventBus` - when acting and replying to incoming event without changing the origin event type and having the routing metadata undefined, the event is sent back to event bus which can cause dead event loop
- **@marblejs/messaging** - `#reply` applies `_UNKNOWN_` tag in case of the origin event/meta doesn't provide `replyTo` attribute - it will prevent sending back the same event type to event bus
```
[ ] Yes
[x] No
```
> fix(messaging): apply unknown tag when replying to event-like message

- jest.config.js
- packages/@integration/src/messaging/client.ts
- packages/@integration/src/messaging/server.ts
- packages/core/src/http/router/http.router.resolver.v2.ts
- packages/core/src/http/server/http.server.event.subscriber.ts
- packages/core/src/http/server/http.server.ts
- packages/messaging/src/server/specs/messaging.server.amqp.spec.ts
- packages/middleware-io/test/io-ws.integration.spec.ts
- packages/middleware-logger/src/logger.handler.ts
- packages/middleware-logger/src/spec/logger.middleware.spec.ts
- packages/websockets/src/server/specs/websocket.server.spec.ts
```
[ ] Bugfix
[ ] Feature
```
- **@marblejs/core** - Corrected RxJS `takeWhile`, `takeUntil` and `take` order as described in [Nicholas Jamieson article](https://ncjamieson.com/avoiding-takeuntil-leaks/).
- Added `node` test environment to `jest` config.
```
[ ] Yes
[x] No
```
> fix(core): RxJS operator order correction + jest "node" environment

- packages/core/src/http/server/http.server.interface.ts
- packages/core/src/listener/listener.interface.ts
- packages/messaging/src/server/messaging.server.interface.ts
- packages/middleware-joi/test/unit/body.spec.ts
- packages/middleware-joi/test/unit/header.spec.ts
- packages/middleware-joi/test/unit/params.spec.ts
- packages/middleware-joi/test/unit/query.spec.ts
- packages/middleware-joi/test/unit/schema.spec.ts
- packages/websockets/src/effects/websocket.effects.interface.ts
- packages/websockets/src/middlewares/websockets.statusLogger.middleware.ts
- packages/websockets/src/server/websocket.server.event.subscriber.ts
- packages/websockets/src/server/websocket.server.event.ts
- packages/websockets/src/server/websocket.server.interface.ts
- packages/websockets/src/server/websocket.server.ts
```
[ ] Bugfix
[x] Feature
```
There is no easy way to subscribe to WebSocket server events, like: `connection`, `error`, etc.
Issue Number: #160 
Developer can subscribe to incoming server events, eg. incoming connections and also watch for broken connections:
```typescript
const connection$: WsServerEffect = (event$, ctx) =>
event$.pipe(
matchEvent(ServerEvent.connection),
tap(event => {
const { client } = event.payload;
client.once('close', () => {
// do some cleanup...
});
}),
);
export const webSocketServer = …
```
> feat(websockets): event handler

- packages/@integration/src/websockets/http.server.ts
- packages/@integration/src/websockets/websockets.server.ts
- packages/middleware-io/test/io-ws.integration.spec.ts
- packages/websockets/src/+internal/websocket.test.util.ts
- packages/websockets/src/index.ts
- packages/websockets/src/middlewares/websockets.statusLogger.middleware.ts
- packages/websockets/src/server/specs/websocket.server.event.spec.ts
- packages/websockets/src/server/specs/websocket.server.spec.ts
- packages/websockets/src/server/websocket.server.event.ts
- packages/websockets/src/server/websocket.server.interface.ts
- packages/websockets/src/server/websocket.server.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #160
- **@marblejs/websockets** - check and kill incoming connections either via HTTP server `upgrade` event or WebSocket `connection` event
- **@marblejs/websockets** - subscribe to closed client connections via `ServerEvent.closeClient` (`"close_client"`)
- **@marblejs/websockets** - additional status logging middleware for detecting closed client connections
- **@marblejs/websockets** - corrected predicates for `noServer` option
- **@marblejs/websockets** - deprecated …
> feat(websockets): subscribe to closed client connections via ServerEvent.closeClient

- packages/middleware-io/package.json
- yarn.lock
This commit bumps the version of io-ts dependency, fixing issues when
using codecs that are defined directly via io-ts in the context of
`requestValidator$`.
```
[X] Bugfix
[ ] Feature
```
Issue Number: #256
Codecs defined via io-ts or marble/middleware-io should now be interchangeable.
```
[ ] Yes
[X] No
```
> fix(middleware-io): incompatible codecs with io-ts

- packages/testing/src/testBed/http/http.testBed.request.spec.ts
- packages/testing/src/testBed/http/http.testBed.request.ts
- packages/testing/src/testBed/http/http.testBed.ts
```
[x] Bugfix
[ ] Feature
```
- **@marblejs/testing** - when no `Content-Type` header is defined the `send` method cannot detect the provided body mime type automatically, causing an error.
- **@marblejs/testing** - corrected `setTestingMetadata` function call
- **@marblejs/testing** - auto detect `Content-Type` when passing HTTP request body 
```
[ ] Yes
[x] No
```
> fix(testing): auto detect `Content-Type` when passing HTTP request body

- packages/core/src/http/response/http.responseBody.factory.ts
- packages/core/src/http/response/http.responseContentType.factory.ts
- packages/core/src/http/response/specs/http.responseBody.factory.spec.ts
```
[x] Bugfix
[x] Feature
```
- **@marblejs/core** - when sending a HTTP response, the handler doesn't detect and transforms `application/x-www-form-urlencoded` body types
- **@marblejs/core** - added support for auto transforming "application/x-www-form-urlencoded" body types if not already "stringified"
-  **@marblejs/core** - auto detect body `Content-Type` for ALL success responses (< 400)
```
[ ] Yes
[x] No
```
> fix(core): bodyFactory - support for "application/x-www-form-urlencoded"

- packages/@integration/test/http.integration.spec.ts
- packages/@integration/test/messaging.integration.spec.ts
- packages/testing/src/testBed/http/http.testBed.interface.ts
- packages/testing/src/testBed/http/http.testBed.request.interface.ts
- packages/testing/src/testBed/http/http.testBed.spec.ts
- packages/testing/src/testBed/http/http.testBed.ts
```
[ ] Bugfix
[x] Feature
```
- **@marblejs/testing** - cleaned up HttpTestBed interface (request builder)
**Previous API:**
```typescript
const testBed = await testBedSetup.useTestBed();
const response = await pipe(
testBed.req('POST'),
testBed.withPath('/api/v1/user'),
testBed.withHeaders({ 'Authorization': 'Bearer FAKE' }),
testBed.withHeaders({ 'Content-Type': 'application/x-www-form-urlencoded' }),
testBed.withBody(data),
testBed.send,
);
```
**New API:**
```typescript
const { request } = await testBedSetup.useTestBed(); …
```
> feat(testing): cleaned up HttpTestBed interface

- packages/core/src/+internal/http/contentType.util.ts
- packages/core/src/+internal/utils/any.util.ts
- packages/core/src/http/response/http.responseBody.factory.ts
- packages/middleware-body/test/bodyParser.integration.spec.ts
- packages/middleware-body/test/bodyParser.integration.ts
- packages/testing/src/testBed/http/http.testBed.response.ts
```
[x] Bugfix
[ ] Feature
```
- **@marblejs/core** - `#bodyFactory` - parse all sort of different `json`-like content types
- **@marblejs/core** - `#bodyFactory` - added missing support for parsing `application/octet-stream` body types
- **@marblejs/testing** - parse response body to string conditionally 
```
[ ] Yes
[x] No
```
> fix(core, testing): incoming/outgoing body parsing

- packages/@integration/src/cqrs/domain/Offer.command.ts
- packages/@integration/src/cqrs/domain/Offer.event.ts
- packages/@integration/src/cqrs/effects/eventbus.effects.ts
- packages/@integration/src/cqrs/effects/http.effects.ts
- packages/@integration/src/cqrs/index.ts
- packages/@integration/tsconfig.json
- packages/core/package.json
- packages/core/src/event/event.interface.ts
- packages/core/src/event/event.spec.ts
- packages/core/src/event/event.ts
- packages/core/src/index.spec.ts
- packages/core/src/index.ts
- packages/core/src/operators/matchEvent/matchEvent.operator.spec.ts
- packages/core/src/operators/matchEvent/matchEvent.operator.ts
- tsconfig.json
- yarn.lock
```
[ ] Bugfix
[x] Feature
```
- **build:** updated tsconfig lib to `ES2020`
- **@marblejs/core**: new I/O `event` decoder (issue: #273)
```
[ ] Yes
[x] No
```
> feat(core): I/O event decoder/encoder

- packages/messaging/src/client/messaging.client.interface.ts
- packages/messaging/src/client/messaging.client.ts
- packages/messaging/src/server/messaging.server.listener.ts
- packages/messaging/src/transport/transport.interface.ts
- packages/messaging/src/transport/transport.transformer.spec.ts
- packages/messaging/src/transport/transport.transformer.ts
```
[x] Bugfix
[x] Feature
```
- **@marblejs/messaging** - if event transformer fails to decode the event, it breaks the listener stream continuity
- **@marblejs/messaging** - if event transformer fails to decode the event it won't break the internal event stream since it will be mapped to `UNKNOWN` event and additionally propagated to `error$`
```
[ ] Yes
[x] No
```
> fix(messaging): map to UNKNOWN event if event decoder fails

- packages/core/src/index.spec.ts
- packages/messaging/src/eventbus/messaging.eventBus.reader.ts
- packages/messaging/src/index.spec.ts
- packages/messaging/src/index.ts
- packages/messaging/src/middlewares/messaging.ack.middleware.ts
- packages/messaging/src/server/messaging.server.listener.ts
- packages/messaging/src/server/specs/messaging.server.amqp.spec.ts
- packages/messaging/src/server/specs/messaging.server.redis.spec.ts
- packages/messaging/src/transport/strategies/amqp.strategy.ts
- packages/messaging/src/transport/strategies/local.strategy.provider.ts
- packages/messaging/src/transport/strategies/local.strategy.ts
- packages/messaging/src/transport/strategies/redis.strategy.ts
- packages/messaging/src/transport/strategies/tcp.strategy.ts
- packages/messaging/src/transport/transport.interface.ts
- packages/messaging/src/transport/transport.provider.ts
- packages/messaging/src/util/messaging.test.util.ts
```
[ ] Bugfix
[x] Feature
```
- **@marblejs/messaging** - transport layer specific options are exposed via `TransportLayerConnection.config.raw`
- **@marblejs/messaging** - register `rejectUnhandled$` as a build-in middleware. From now there is no need to register it manually in each supported transport layer.
```
[ ] Yes
[x] No
```
> feat(messaging): expose transport layer raw options

- packages/core/src/+internal/utils/error.util.ts
- packages/core/src/operators/act/act.operator.spec.ts
- packages/core/src/operators/act/act.operator.ts
- packages/messaging/src/middlewares/messaging.eventLogger.middleware.ts
- packages/messaging/src/middlewares/messaging.eventOutput.middleware.ts
- packages/messaging/src/server/messaging.server.listener.ts
```
[ ] Bugfix
[x] Feature
```
- **@marblejs/core** - `act` - pass through error events. It allows us to build the following flow:
```typescript
event$.pipe(
matchEvent(Codec),
act(eventValidator$(Codec)),
act(event => ...),
);
```
With this feature we can trigger subsequent `act` error handler if previous `act` operator did not handled the exception.
- **@marblejs/messaing** - server doesn't have to skip error events since `act` operator maps default errors to `*_UNHANDLED_ERROR` suffixed event types to avoid event handler dead …
> feat(core): act - pass through error events

- packages/core/src/context/context.helper.ts
- packages/core/src/context/context.ts
- packages/core/src/context/specs/context.spec.ts
- packages/messaging/src/eventbus/messaging.eventBus.reader.ts
```
[ ] Bugfix
[x] Feature
```
- **@marblejs/messaging** - `EventBus` initializes the reader with the **copy** of derived context, eg. HttpServer context. Marble.js dependency injection container (aka Context) is built around JS Map. When removing a token from the context, references are changed because the whole Map is cloned.
```typescript
// the problem 👇 - new Context copy
const derivedContext = deleteAt(setoidContextToken)(SomeToken)(rootContext);
const context = await constructContext(derivedContext)( …
```
> feat(core): derived context

- packages/messaging/src/middlewares/messaging.eventOutput.middleware.spec.ts
- packages/messaging/src/middlewares/messaging.eventOutput.middleware.ts
```
[x] Bugfix
[ ] Feature
```
- **@marblejs/messaging** - `outputErrorEncoder$` crashes when `event.payload === null`
```
[ ] Yes
[x] No
```
> fix(messaging): outputErrorEncoder$ - "null" payload case

- packages/core/src/context/context.helper.ts
- packages/core/src/context/context.ts
- packages/core/src/context/specs/context.helper.spec.ts
- packages/core/src/context/specs/context.spec.ts
```
[x] Bugfix
[ ] Feature
```
- **@marblejs/messaging** - `eventBus` registers two `LoggerToken` dependencies - one for main context, second for derived context. If custom logger is bound to derived context `LoggerToken`, then first/redundant binding is used instead.
- **@marblejs/core** - `constructContext` helper function registers only one `LoggerToken` if already present in derived context
```
[ ] Yes
[x] No
```
> fix(core): context - unset redundant token if present in DerivedContext

- packages/core/src/logger/logger.interface.ts
- packages/messaging/src/middlewares/messaging.eventLogger.middleware.spec.ts
- packages/messaging/src/middlewares/messaging.eventLogger.middleware.ts
```
[ ] Bugfix
[x] Feature
```
Currently it is not possible to log the detailed information about the event payload. 
The event `payload` is passed to the `LoggerOptions` inside `data` object in input and output logger middlewares. This information can be then extracted inside logger implementation and outputted to the console.
```
[ ] Yes
[x] No
```
> feat(messaging): pass event payload to input and output logger

- packages/core/src/http/router/http.router.resolver.v2.ts
- packages/core/src/http/router/specs/http.router.resolver.v2.spec.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #309 
- `@marblejs/core` - In case of malformed url error, instead of crashing the whole server it keeps running stable and returns a Bad-Request error.
```
[ ] Yes
[x] No
```
> fix(core): router resolver - malformed URI error handling

- .eslintrc.js
- package.json
- packages/core/src/+internal/testing/http.helper.ts
- packages/core/src/http/effects/http.effects.factory.ts
- packages/core/src/http/effects/specs/http.effects.factory.spec.ts
- packages/core/src/http/response/http.responseBody.factory.ts
- packages/core/src/http/router/specs/http.router.combiner.spec.ts
- packages/core/src/index.spec.ts
- packages/core/src/index.ts
- packages/middleware-body/test/bodyParser.integration.ts
- packages/middleware-cors/src/configurePreflightResponse.ts
- packages/middleware-cors/src/middleware.ts
- packages/middleware-io/test/io-http.integration.ts
- packages/middleware-joi/src/index.ts
- packages/middleware-joi/test/helpers/api.spec-util.ts
- packages/middleware-joi/test/unit/body.spec.ts
- packages/middleware-joi/test/unit/header.spec.ts
- packages/middleware-joi/test/unit/params.spec.ts
- packages/middleware-joi/test/unit/query.spec.ts
- packages/middleware-joi/test/unit/schema.spec.ts
- yarn.lock
```
[ ] Bugfix
[ ] Feature
```
- show eslint deprecation warnings
- corrected + suppresed selected `EffectFactory` deprecation warns
- corrected `util` package deprecation warnings
- **middleware-joi**: suppresd selected deprecation warnings
- **core**: removed deprecated `createHttpServerTestBed`utility
```
[ ] Yes
[x] No
```
> build: show and correct eslint deprecation warnings

- packages/websockets/package.json
```
[x] Bugfix
[ ] Feature
```
Issue Number: #346 
- **@marblejs/websockets** - added `path-to-regexp` package to the dependency list
```
[ ] Yes
[x] No
```
> fix(websockets): added `path-to-regexp` package to the dependency list

- packages/core/src/+internal/utils/any.util.ts
- packages/core/src/+internal/utils/env.util.ts
- packages/core/src/+internal/utils/index.ts
- packages/core/src/+internal/utils/spec/env.util.spec.ts
- packages/http/src/+internal/header.util.spec.ts
- packages/http/src/+internal/header.util.ts
- packages/http/src/response/http.responseHandler.ts
- packages/http/src/response/http.responseHeaders.factory.ts
- packages/http/src/response/specs/http.responseHandler.spec.ts
- packages/http/src/response/specs/http.responseHeaders.factory.spec.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #311
- all HTTP headers are lower cased (normalized) unless `MARBLE_HTTP_HEADERS_NORMALIZATION` environment variable is set to `false`
```
[x] Yes
[ ] No
```
> feat(http): normalize HTTP headers

- packages/core/src/+internal/utils/any.util.ts
- packages/http/src/response/http.responseHeaders.factory.ts
- packages/http/src/response/specs/http.responseHeaders.factory.spec.ts
```
[x] Bugfix
[ ] Feature
```
- **@marblejs/http** - correctly calculate `Content-Length` for an empty object
```
[ ] Yes
[x] No
```
> fix(http): correctly calculate `Content-Length` for an empty object

- jest.config.js
- package.json
- packages/core/src/+internal/files/fileReader.helper.spec.ts
- packages/http/src/error/http.error.model.ts
- packages/http/src/router/http.router.resolver.ts
- packages/http/src/router/specs/http.router.resolver.spec.ts
- packages/http/src/server/http.server.spec.ts
- packages/messaging/src/eventbus/messaging.eventBus.reader.spec.ts
- packages/messaging/src/server/specs/messaging.server.amqp.spec.ts
- packages/messaging/src/server/specs/messaging.server.redis.spec.ts
- packages/messaging/src/util/messaging.test.util.ts
- packages/middleware-body/src/specs/body.middleware.spec.ts
- packages/middleware-io/test/io-ws.integration.spec.ts
- packages/middleware-logger/src/spec/logger.util.spec.ts
- packages/websockets/src/server/specs/websocket.server.event.spec.ts
- packages/websockets/src/server/specs/websocket.server.spec.ts
- scripts/test-helpers.js
- yarn.lock
```
[ ] Bugfix
[x] Feature
```
- **all**: Typescript v4.4 support 
```
[ ] Yes
[x] No
```
> feat: typescript v4.4 support

- .commitlintrc.js
- packages/testing/src/testBed/http/http.testBed.response.ts
- packages/testing/src/testBed/http/http.testBed.spec.ts
```
[x] Bugfix
[ ] Feature
```
- **@marblejs/testing** - parses response body to an empty string if nothing is provided and the `Content-Type` is `application/json`
- **@marblejs/testing** - parse response body to `undefined` if nothing is provided and the `Content-Type` is `application/json`
```
[ ] Yes
[x] No
```
> fix(testing): parse response body to undefined if not provided in case of "application/json" header

- package.json
- packages/@integration/package.json
- packages/core/package.json
- packages/http/package.json
- packages/messaging/package.json
- packages/messaging/src/ack/ack.ts
- packages/messaging/src/server/specs/messaging.server.redis.spec.ts
- packages/middleware-body/package.json
- packages/middleware-cors/package.json
- packages/middleware-io/package.json
- packages/middleware-logger/package.json
- packages/middleware-multipart/package.json
- packages/testing/package.json
- packages/websockets/package.json
- yarn.lock
```
[ ] Bugfix
[x] Feature
```
When calling `ackMessage` / `nackMesage` in case of **redis** strategy the listener returns an errored event together with a respective error log.
- upgraded `rxjs`, `fp-ts`, `io-ts` to the latest supported version (closes: #396)
- rxjs - `^7.5.7`
- fp-ts - `^2.13.1`
- io-ts - `^2.2.19`
- When calling `ackMessage` / `nackMesage` in case of **redis** strategy the listener doesn't return an errored event, instead only a respective error log, so that the related effect can run without any disturbance …
> feat(messaging): dependencies upgrade + "redis" strategy unsupported methods error handling
